---

- alias: "Leaving Home"
  id: b53f7fa0-502e-42dc-ba0a-0599f2de3c16
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  condition:
    - "{{ is_state('input_boolean.guest_mode', 'off') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - climate.living_room
          - light.all_lights
          - media_player.tv
          - fan.master_bedroom_fan
    - delay: 30
    - service: notify.family
      data:
        title: "Closed everything for you"
        message: >-
          "Your lights are {{ states('light.all_lights') }}, AC is {{ states('climate.living_room') }}, TV is {{ states('media_player.tv') }} and the shutter is now {{ states('cover.living_room_shutter') }}"
