---

- alias: "Leaving Home"
  id: b53f7fa0-502e-42dc-ba0a-0599f2de3c16
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  condition:
    - "{{ is_state('input_boolean.guest_mode', 'off') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - climate.living_room
          - switch.boiler
          - switch.kids_socket
          - light.all_lights
          - fan.ceiling_fans
          - remote.tv
    - service: cover.close_cover
      data:
        entity_id: cover.living_room_shutter
    - service: system_bridge.power_command
      continue_on_error: true
      data:
        command: shutdown
        bridge: 5946df1a296aaa3a0ee88fc8d1a73861
    - delay: 30
    - service: notify.family
      data:
        title: "I'll be missing you."
        message: >-
          Lights are {{ states('light.all_lights') }}.
          AC is {{ states('climate.living_room') }}.
          Boiler is {{ states('switch.boiler') }}.
          Shutter is now {{ states('cover.living_room_shutter') }}.
