---

- alias: "Leaving Home"
  id: b53f7fa0-502e-42dc-ba0a-0599f2de3c16
  trigger:
    trigger: state
    entity_id: group.person
    to: 'not_home'
  condition:
    - "{{ is_state('input_boolean.guest_mode', 'off') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    - action: homeassistant.turn_off
      data:
        entity_id:
          - climate.living_room
          - climate.master_bedroom_ac
          - switch.boiler
          - switch.kids_socket
          - light.all_lights
          - fan.ceiling_fans
          - remote.tv
    - action: cover.close_cover
      data:
        entity_id: cover.living_room_shutter
    - delay: 30
    - action: notify.family
      data:
        title: "I'll be missing you."
        message: >-
          Lights are {{ states('light.all_lights') }}.
          Main AC is {{ states('climate.living_room') }}, and the Bedroom AC is {{ states('climate.master_bedroom_ac') }}
          Boiler is {{ states('switch.boiler') }}.
          Shutter is now {{ states('cover.living_room_shutter') }}.
