---

- alias: "Leaving Home"
  id: b53f7fa0-502e-42dc-ba0a-0599f2de3c16
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  condition:
    - "{{ is_state('input_boolean.guest_mode', 'off') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id:
          - climate.living_room
          - switch.boiler
          - switch.deltaco_sh_p02_socket_1
          - switch.deltaco_sh_p02_socket_2
          - light.all_lights
          - media_player.tv
          - fan.master_bedroom_fan
    - service: cover.close_cover
      data:
        entity_id: cover.living_room_shutter
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.home
    - delay: 30
    - service: notify.family
      data:
        title: "I'll be missing you."
        message: >-
          "The current state of your Devices is:
          Lights: {{ states('light.all_lights') }}
          AC: {{ states('climate.living_room') }}
          TV: {{ states('media_player.tv') }}
          Boiler: {{ states('switch.boiler') }}
          Shutter: {{ states('cover.living_room_shutter') }}
          Alarm: {{ states('alarm_control_panel.home') }}"
