---

- alias: "Shabbat - Disable Shabbat mode on weekday"
  id: cbf11d36-cf0a-4442-a111-73b01906303c
  trigger:
    platform: homeassistant
    event: start
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.shabbat_mode
