---

- alias: "System Bridge - Shutdown Laptop"
  id: 92e4c11c-d524-4db4-a61d-8f6479a9a3e6
  trigger:
    platform: state
    entity_id: input_button.shutdown_laptop
  action:
    service: system_bridge.power_command
    data:
      command: shutdown
      bridge: 5946df1a296aaa3a0ee88fc8d1a73861
