---

- alias: "Washing machine - Set state"
  id: 860cd025-6d01-4ade-b19f-6e65b0cef62e
  trigger:
    - trigger: numeric_state
      entity_id: sensor.washing_machine_dd774f_current
      below: 1
      for:
        minutes: 20
      id: 'off'
    - trigger: numeric_state
      entity_id: sensor.washing_machine_dd774f_current
      above: 3
      id: 'running'
    - trigger: numeric_state
      entity_id: sensor.washing_machine_dd774f_current
      below: 1
      for:
        minutes: 10
      id: 'finished'
  action:
    choose:
      - conditions:
          condition: trigger
          id: 'off'
        sequence:
          - action: input_select.select_option
            target:
              entity_id: input_select.washing_machine_state
            data:
              option: 'Off'
          - action: input_boolean.turn_off
            entity_id: input_boolean.washing_machine_started
      - conditions:
          - condition: trigger
            id: 'finished'
          - "{{ is_state('input_select.washing_machine_state', 'Running') }}"
        sequence:
          action: input_select.select_option
          target:
            entity_id: input_select.washing_machine_state
          data:
            option: 'Finished'
      - conditions:
          condition: trigger
          id: 'running'
        sequence:
          - if:
              condition: state
              entity_id: input_boolean.washing_machine_started
              state: 'off'
            then:
              - action: input_boolean.turn_on
                entity_id: input_boolean.washing_machine_started
              - action: timer.start
                target:
                  entity_id: timer.washing_machine_working
          - action: input_select.select_option
            target:
              entity_id: input_select.washing_machine_state
            data:
              option: 'Running'
