---

- alias: "Washing machine - Set state"
  id: 860cd025-6d01-4ade-b19f-6e65b0cef62e
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_energy_current
      below: 1
      for:
        minutes: 20
      id: 'off'
    - platform: numeric_state
      entity_id: sensor.washing_machine_energy_current
      above: 3
      id: 'running'
    - platform: numeric_state
      entity_id: sensor.washing_machine_energy_current
      below: 1
      for:
        minutes: 10
      id: 'finished'
  action:
    choose:
      - conditions:
          - condition: trigger
            id: 'off'
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.washing_machine_state
            data:
              option: 'Off'
      - conditions:
          - condition: trigger
            id: 'finished'
          - "{{ is_state('input_select.washing_machine_state', 'Running') }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.washing_machine_state
            data:
              option: 'Finished'
      - conditions:
          - condition: trigger
            id: 'running'
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.washing_machine_state
            data:
              option: 'Running'

- alias: "Washing machine - start timer"
  id: 7b9608a5-cffc-4ba5-b7f5-8a2f8ae6f224
  trigger:
    - platform: state
      entity_id: input_select.washing_machine_state
      to: 'Running'
  action:
    service: timer.start
    target:
      entity_id: timer.washing_machine_working
