---

- name: "Shabbat eve"
  icon: mdi:candle
  entities:
    switch.shabbat_mode:
      state: 'on'
    # light.room_lights:
    #   state: 'off'
    light.living_room_lights:
      state: 'on'
      brightness: 230
    light.kitchen_ceiling_light:
      state: 'on'
      brightness: 230
    light.bathroom_light:
      state: 'on'
    light.corridor_light:
      state: 'off'
    # light.important_lights:
    #   state: 'on'
    #   brightness_pct: 70
    #   kelvin: 4000
    # light.kids_ambient_lights:
    #   state: 'on'
    #   effect: 'Colortwinkles'
