---

- platform: template
  switches:
    guest_mode:
      unique_id: b9b2b3db-bcc9-4d44-8720-faa8515add80
      friendly_name: "Guest mode"
      value_template: >-
        {{ states('input_boolean.guest_mode') }}
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.guest_mode
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.guest_mode
      icon_template: mdi:human-greeting
