---

- rgb_color:
      - 217
      - 76
      - 100
  transition: 1
- rgb_color:
      - 76
      - 217
      - 100
  transition: 1
- rgb_color:
      - 0
      - 255
      - 255
  transition: 1
- rgb_color:
      - 76
      - 100
      - 217
  transition: 1
