---

- alias: "Vacuum - Set to 'cleaned today'"
  id: 8d53ce02-066c-4a51-a369-3e13d1220cee
  trigger:
    - platform: state
      entity_id: vacuum.roborock_s7
      to: 'cleaning'
      for: '00:10:00'
      id: 'set'
    - platform: time
      at: '00:00:00'
      id: 'reset'
  action:
    choose:
      - conditions:
          condition: trigger
          id: 'set'
        sequence:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.cleaned_today
      - conditions:
          condition: trigger
          id: 'reset'
        sequence:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.cleaned_today

- alias: "Vacuum - Intelligent mode switch"
  id: c8258c50-16dd-4b3d-b743-7a806bdb1018
  trigger:
    - platform: state
      entity_id: group.person
      to: 'not_home'
      id: 'turbo'
    - platform: state
      entity_id: group.person
      to: 'home'
      id: 'quiet'
  action:
    choose:
      - conditions:
          - condition: trigger
            id: 'turbo'
          - "{{ is_state('input_boolean.guest_mode', 'off') }}"
        sequence:
          service: vacuum.set_fan_speed
          data:
            fan_speed: "turbo"
          target:
            entity_id: vacuum.roborock_s7
      - conditions:
        - condition: trigger
          id: 'quiet'
        sequence:
          service: vacuum.set_fan_speed
          data:
            fan_speed: "quiet"
          target:
            entity_id: vacuum.roborock_s7

- alias: "Vacuum - Set Vacuum Fan Speed"
  id: 6c1cb638-04fb-43c3-bf7a-a062c6289122
  trigger:
    - platform: state
      entity_id: input_select.vacuum_fan_speed_list
  action:
    service: >
      {% if is_state("input_select.vacuum_fan_speed_list", "Off") %}
        vacuum.set_fan_speed
      {% elif is_state("input_select.vacuum_fan_speed_list", "Quiet") %}
        vacuum.set_fan_speed
      {% elif is_state("input_select.vacuum_fan_speed_list", "Balanced") %}
        vacuum.set_fan_speed
      {% elif is_state("input_select.vacuum_fan_speed_list", "Turbo") %}
        vacuum.set_fan_speed
      {% elif is_state("input_select.vacuum_fan_speed_list", "Max") %}
        vacuum.set_fan_speed
      {% elif is_state("input_select.vacuum_fan_speed_list", "Custom") %}
        vacuum.set_fan_speed
      {% endif %}
    data:
      entity_id: vacuum.roborock_s7
      fan_speed: "{{ states('input_select.vacuum_fan_speed_list') }}"
