---

- alias: "Vacuum - Set to 'cleaned today'"
  id: 8d53ce02-066c-4a51-a369-3e13d1220cee
  trigger:
    - platform: state
      entity_id: vacuum.roborock_s7
      to: 'cleaning'
      for: '00:10:00'
      id: 'set'
    - platform: time
      at: '00:00:00'
      id: 'reset'
  action:
    choose:
      - conditions:
          condition: trigger
          id: 'set'
        sequence:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.cleaned_today
      - conditions:
          condition: trigger
          id: 'reset'
        sequence:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.cleaned_today

- alias: "Vacuum - Intelligent mode switch"
  id: c8258c50-16dd-4b3d-b743-7a806bdb1018
  trigger:
    - platform: state
      entity_id: group.person
      to: 'not_home'
      id: 'turbo'
    - platform: state
      entity_id: group.person
      to: 'home'
      id: 'silent'
  action:
    choose:
      - conditions:
          - condition: trigger
            id: 'turbo'
          - "{{ is_state('input_boolean.guest_mode', 'off') }}"
        sequence:
          service: script.vacuum_set_turbo
      - conditions:
        - condition: trigger
          id: 'silent'
        sequence:
          service: script.vacuum_set_silent

- alias: "Vacuum - Set mode"
  id: 339c44db-f51b-4174-b396-18e69213b4e7
  trigger:
    platform: state
    entity_id: input_select.vacuum_fan_speed_list
  action:
    service: >-
      {% if trigger.to_state.state == 'Silent' %}
        script.vacuum_set_silent
      {% elif trigger.to_state.state == 'Standard' %}
        script.vacuum_set_standard
      {% elif trigger.to_state.state == 'Medium' %}
        script.vacuum_set_medium
      {% elif trigger.to_state.state == 'Turbo' %}
        script.vacuum_set_turbo
      {% endif %}
