---

- platform: template
  sensors:
    count_automations:
      friendly_name: "Automations"
      icon_template: mdi:autorenew
      value_template: >-
        {{ states.automation | count }}
    count_binary_sensors:
      friendly_name: "Binary Sensors"
      icon_template: mdi:unfold-more-horizontal
      value_template: >-
        {{ states.binary_sensor | count }}
    count_climates:
      friendly_name: "Climate"
      icon_template: mdi:air-conditioner
      value_template: >-
        {{ states.climate | count }}
    count_device_trackers:
      friendly_name: "Device Trackers"
      icon_template: mdi:map-marker
      value_template: >-
        {{ states.device_tracker | count }}
    count_entities:
      friendly_name: "Entities"
      icon_template: mdi:format-list-bulleted-square
      value_template: >-
        {{ states | count }}
    count_input_booleans:
      friendly_name: "Input Boolean"
      icon_template: mdi:toggle-switch
      value_template: >-
        {{ states.input_boolean | count }}
    count_input_datetimes:
      friendly_name: "Date-Time"
      icon_template: mdi:timetable
      value_template: >-
        {{ states.input_datetime | count }}
    count_input_selects:
      friendly_name: "Input Select"
      icon_template: mdi:view-list
      value_template: >-
        {{ states.input_select | count }}
    count_lights:
      friendly_name: "Lights"
      icon_template: mdi:lightbulb-group
      value_template: >-
        {{ states.light | count }}
    count_scripts:
      friendly_name: "Scripts"
      icon_template: mdi:script-text-outline
      value_template: >-
        {{ states.script | count }}
    count_sensors:
      friendly_name: "Sensors"
      icon_template: mdi:resistor
      value_template: >-
        {{ states.sensor | count }}
    count_switches:
      friendly_name: "Switches"
      icon_template: mdi:light-switch
      value_template: >-
        {{ states.switch | count }}
    count_timers:
      friendly_name: "Timers"
      icon_template: mdi:timer-outline
      value_template: >-
        {{ states.timer | count }}
    count_zones:
      friendly_name: "Zones"
      icon_template: mdi:map-marker-radius
      value_template: >-
        {{ states.zone | count }}
