---

# Android devices report the alarm by the time it will fire a notification about upcoming alarm
# It is usually 30 to 10 minutes before the actual alarm will trigger
# the sensors below compansate for it and returning the correct value
# you can change the value below to the correct offset of your device
- platform: template
  sensors:
    tohar_next_alarm_formatted:
      friendly_name: 'Tohar next Alarm'
      value_template: >-
        {{
          ((as_timestamp(
            states('sensor.tohar_next_alarm')
          ) | int) + ( 15*60 )) | timestamp_custom('%H:%M')
        }}
      icon_template: mdi:alarm
    yuval_next_alarm_formatted:
      friendly_name: 'Yuval next Alarm'
      value_template: >-
        {{
          ((as_timestamp(
            states('sensor.yuval_next_alarm')
          ) | int) + ( 15*60 )) | timestamp_custom('%H:%M')
        }}
      icon_template: mdi:alarm
