---

- platform: mold_indicator
  name: "Bathroom Mold Indicator"
  indoor_temp_sensor: sensor.bathroom_temperature
  indoor_humidity_sensor: sensor.bathroom_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0

- platform: mold_indicator
  name: "Ensuite Mold Indicator"
  indoor_temp_sensor: sensor.ensuite_temperature
  indoor_humidity_sensor: sensor.ensuite_humidity
  outdoor_temp_sensor: sensor.openweathermap_temperature
  calibration_factor: 2.0
