---

- platform: steam_online
  api_key: !secret steam_api
  accounts:
    - 76561198173612681

- platform: template
  sensors:
    steam_game:
      friendly_name: "Steam Game"
      value_template: >-
        {{ state_attr('sensor.steam_76561198173612681', 'game') }}
      icon_template: mdi:gamepad-square-outline

- platform: history_stats
  name: "Track Steam playtime"
  entity_id: binary_sensor.steam_game_on
  state: 'on'
  type: time
  start: >-
    {{ now().replace(hour=0).replace(minute=0).replace(second=0) }}
  end: >-
    {{ now() }}
- platform: template
  sensors:
    track_steam_playtime_formatted:
      friendly_name: "Formatted Steam playtime"
      value_template: >-
        {% set hours = states('sensor.track_steam_playtime') | float %}
        {% set minutes = ((hours % 1) * 60) | int %}
        {% set hours = (hours - (hours % 1)) | int %}
        {{ '%02i.%02i'%(hours, minutes) }}
      icon_template: mdi:steam
