---

- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: load_5m
    - type: memory_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: throughput_network_in
      arg: enp1s0
    - type: throughput_network_out
      arg: enp1s0
    - type: last_boot
