---

- platform: template
  sensors:
    ups_time_remaining:
      friendly_name: "UPS Time remaining"
      value_template: >-
        {{ (states('sensor.ups_battery_runtime') | int) // 60 }}
      icon_template: >-
        {% if is_state('sensor.ups_status', 'Online') %}
        mdi:battery-charging
        {%else%}
        mdi:battery-alert
        {%endif%}
      unit_of_measurement: 'minutes'
      device_class: 'battery'
    ups_load_watts:
      friendly_name: "UPS Load"
      value_template: >-
        {{
          (states('sensor.ups_load')|int * 0.01 * states('sensor.ups_nominal_power')|int * 0.8) | round(1)
        }}
      icon_template: mdi:current-dc
      unit_of_measurement: 'Watts'
      device_class: 'power'
