---

# Climate
#########
living_room_ac_total_energy_usage_daily:
  source: sensor.living_room_ac_power_consumption
  cycle: daily
living_room_ac_total_energy_usage_weekly:
  source: sensor.living_room_ac_power_consumption
  cycle: weekly
living_room_ac_total_energy_usage_monthly:
  source: sensor.living_room_ac_power_consumption
  cycle: monthly

master_bedroom_ac_total_energy_usage_daily:
  source: sensor.master_bedroom_ac_power_consumption
  cycle: daily
master_bedroom_ac_total_energy_usage_weekly:
  source: sensor.master_bedroom_ac_power_consumption
  cycle: weekly
master_bedroom_ac_total_energy_usage_monthly:
  source: sensor.master_bedroom_ac_power_consumption
  cycle: monthly

total_ac_energy_usage_daily:
  source: sensor.total_ac_power_consumption
  cycle: daily
total_ac_energy_usage_weekly:
  source: sensor.total_ac_power_consumption
  cycle: weekly
total_ac_energy_usage_monthly:
  source: sensor.total_ac_power_consumption
  cycle: monthly
