---

- platform: template
  sensors:
    vacuum_status:
      friendly_name: "Status"
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'status') }}
      icon_template: >-
        {% set status = state_attr('vacuum.xiaomi_vacuum_cleaner', 'status') %}
        {% if status == 'Charging' %}
          mdi:battery-charging
        {% elif status == 'Cleaning' %}
          mdi:move-resize
        {% elif status == 'Returning home' %}
          mdi:home-import-outline
        {% elif status == 'Idle' %}
          mdi:dots-horizontal
        {% elif status == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_fan_speed:
      friendly_name: "Fan Speed"
      value_template: >-
        {% set speed = state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') %}
        {% if speed == 'Silent' %}
          Silent
        {% elif speed == 'Standard' %}
          Standard
        {% elif speed == 'Medium' %}
          Medium
        {% elif speed == 'Turbo' %}
          Turbo
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% set speed = state_attr('vacuum.xiaomi_vacuum_cleaner', 'fan_speed') %}
        {% if speed == 'Silent' %}
          mdi:fan-speed-1
        {% elif speed == 'Standard' %}
          mdi:fan-speed-2
        {% elif speed == 'Medium' %}
          mdi:fan-speed-3
        {% elif speed == 'Turbo' %}
          mdi:weather-tornado
        {% else %}
          mdi:alert-circle
        {% endif %}
    vacuum_battery:
      friendly_name: "Vacuum Battery"
      icon_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_icon') }}
      unit_of_measurement: '%'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'battery_level') }}
    vacuum_area_cleaned:
      friendly_name: "Area of Last Cycle"
      icon_template: mdi:ruler
      unit_of_measurement: 'm²'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaned_area') }}
    vacuum_time_cleaned:
      friendly_name: "Time of Last Cycle"
      icon_template: mdi:timer
      unit_of_measurement: 'minutes'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'cleaning_time') }}
    vacuum_last_cleaned:
      friendly_name: "Last cleaned"
      icon_template: mdi:timetable
      value_template: >-
        {{
          as_timestamp(
            state_attr('vacuum.xiaomi_vacuum_cleaner', 'clean_stop')
          ) |
          timestamp_custom("%A, %H:%M", true)
        }}
    vacuum_clean_cliff_sensors:
      friendly_name: "Clean sensor"
      icon_template: mdi:broom
      unit_of_measurement: 'hours'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'sensor_dirty_left') }}
    vacuum_clean_filter:
      friendly_name: "Replace filter"
      icon_template: mdi:screwdriver
      unit_of_measurement: 'hours'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'filter_left') }}
    vacuum_clean_main_brush:
      friendly_name: "Replace main brush"
      icon_template: mdi:screwdriver
      unit_of_measurement: 'hours'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'main_brush_left') }}
    vacuum_clean_side_brush:
      friendly_name: "Replace side brush"
      icon_template: mdi:screwdriver
      unit_of_measurement: 'hours'
      value_template: >-
        {{ state_attr('vacuum.xiaomi_vacuum_cleaner', 'side_brush_left') }}
