---

- platform: history_stats
  name: "Yuval - Time at work"
  entity_id: person.yuval
  state: "Hirsh"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "Yuval - Time at IDF"
  entity_id: person.yuval
  state:
    - "Nahshonim"
    - "Front"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "Tohar - Time at work"
  entity_id: person.tohar
  state:
    - "Melody"
    - "Gelato"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0) }}"
  end: "{{ now() }}"
