- id: '1652034222704'
  alias: Send actionable notifications for Android
  description: ''
  use_blueprint:
    path: vorion/actionable-notifications-for-android.yaml
    input:
      second_action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.at_home
      notify_device: a2af0c46177d1a180dc3590956202f0c
      trigger_entity: binary_sensor.shabbat_30_min_notification_trigger
      persistent_notification: true
      first_action:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.at_home
      action_1_title: בבית
      action_2_title: לא בבית
      notification_title: שבת בבית?
