##################################################
#     Home Assistant Main Configuration File     #
#            Yuval Aboulafia - 202410            #
##################################################
#                      CORE                      #
##################################################
homeassistant:
  internal_url: !secret internal_url
  allowlist_external_dirs:
    - /config
  media_dirs:
    local: /config/www
config:
cloud:
my:

##################################################
#                       GUI                      #
##################################################
energy:
frontend:
  themes: !include_dir_merge_named themes
lovelace:
system_health:
homeassistant_alerts:

##################################################
#                     PERSONS                    #
##################################################
person:

##################################################
#                   DISCOVERY                    #
##################################################
zeroconf:
ssdp:

##################################################
#                  INTEGRATIONS                  #
##################################################
assist_pipeline:
automation: !include_dir_merge_list automation
backup:
binary_sensor: !include_dir_merge_list components/binary_sensor
button:
# camera: !include_dir_merge_list components/camera
counter:
device_tracker:
group: !include_dir_merge_named components/group
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
media_source:
mobile_app:
mqtt: !include_dir_merge_named components/mqtt
notify: !include_dir_merge_list components/notify
schedule:
scene: !include_dir_merge_list scene
script: !include ./scripts.yaml
sensor: !include_dir_merge_list components/sensor
template: !include_dir_merge_list components/template
timer:
tts:
utility_meter:
zone:

gree_silent:
  target_macs:
    - "94:24:b8:b6:28:d6"

##################################################
#                  LOG COMPONENTS                #
##################################################
history:
logbook: !include components/logging/logbook.yaml
recorder: !include components/logging/recorder.yaml
logger:
  default: warning
  logs:
    homeassistant.components.androidtv_remote: error
    homeassistant.components.cast: error
    pychromecast.socket_client: error
system_log:
  fire_event: true
