---

decluttering_templates:
  !include_dir_merge_named lovelace/decluttering_cards

title: "Aboulafia Home"
views:
  - !include lovelace/ui-lovelace/overview.yaml
#  - !include lovelace/ui-lovelace/floorplan.yaml
  - !include lovelace/ui-lovelace/living_room.yaml
  - !include lovelace/ui-lovelace/master_bedroom.yaml
#  - !include lovelace/ui-lovelace/bedroom.yaml
  - !include lovelace/ui-lovelace/bathroom.yaml
  - !include lovelace/ui-lovelace/home_office.yaml
  - !include lovelace/ui-lovelace/stats.yaml
  - !include lovelace/ui-lovelace/monitoring.yaml
  - !include lovelace/ui-lovelace/system.yaml
  - !include lovelace/ui-lovelace/homelab.yaml
  - !include lovelace/ui-lovelace/devices.yaml
  - !include lovelace/ui-lovelace/doorbell.yaml
