---

decluttering_templates:
  !include_dir_merge_named lovelace/decluttering_cards

title: "Aboulafia Home"
views:
  - !include lovelace/interface/overview.yaml
#  - !include lovelace/interface/floorplan.yaml
  - !include lovelace/interface/living_room.yaml
  - !include lovelace/interface/master_bedroom.yaml
#  - !include lovelace/interface/bedroom.yaml
  - !include lovelace/interface/bathroom.yaml
  - !include lovelace/interface/home_office.yaml
  - !include lovelace/interface/stats.yaml
  - !include lovelace/interface/monitoring.yaml
  - !include lovelace/interface/system.yaml
  - !include lovelace/interface/homelab.yaml
  - !include lovelace/interface/devices.yaml
  - !include lovelace/interface/doorbell.yaml
