---

- alias: "Boiler - Turn-on when in gym"
  id: e7f1d529-6331-4cdc-94e3-3cc5e3e24142
  trigger:
    platform: state
    entity_id: person.tohar
    to: gym
    for:
      minutes: 10
  action:
    service: switch.turn_on
    data:
      entity_id: switch.boiler
