---
version: '3.6'

services:
  homeassistant:
    hostname: homeassistant
    container_name: "homeassistant"
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /home/homeassistant/homeassistant/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    # devices:
    #    - /dev/i2c-0:/dev/i2c-0
    ports:
      - 8123:8123
    restart: always

  esphome:
    container_name: "esphome"
    image: esphome/esphome
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Asia/Jerusalem
    ports:
      - 6052:6052
    restart: unless-stopped
    volumes:
      - /home/homeassistant/esphome/config:/config

  mqtt:
    image: library/eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - /home/homeassistant/mosquitto/config/:/mosquitto/config
      - /home/homeassistant/mosquitto/data:/mosquitto/data
      - /home/homeassistant/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  zigbee2mqtt:
    container_name: "zigbee2mqtt"
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/homeassistant/zigbee2mqtt/:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Jerusalem
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  unifi-controller:
    image: lscr.io/linuxserver/unifi-controller
    container_name: "unifi-controller"
    volumes:
      - /home/homeassistant/unifi/config:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514
    restart: unless-stopped
