---
version: '3.4'

services:
  homeassistant:
    restart: always
    # depends_on:
    #   - postgres
    hostname: homeassistant
    container_name: "homeassistant"
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /home/dev/homeassistant/homeassistant/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    # devices:
    #    - /dev/i2c-0:/dev/i2c-0
    network_mode: host
    # dns:
    #   - ${PIHOLE}

  # postgres:
  #   restart: always
  #   hostname: postgres
  #   container_name: "postgres"
  #   image: postgres:latest
  #   network_mode: host
  #   # ports:
  #   #   - 5432:5432
  #   environment:
  #     PUID: ${LOCAL_USER}
  #     PGID: ${LOCAL_USER}
  #     TZ: 'Asia/Jerusalem'
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: HADB
  #   volumes:
  #     - /home/homeassistant/postgres/data:/var/lib/postgresql/data

  # portainer:
  #   hostname: portainer
  #   container_name: portainer
  #   image: portainer/portainer-ce:latest
  #   restart: always
  #   network_mode: bridge
  #   ports:
  #       - '9000:9000'
  #   environment:
  #       TZ: "Asia/Jerusalem"
  #   volumes:
  #       - /var/run/docker.sock:/var/run/docker.sock

  # unifi-controller:
  #   image: ghcr.io/linuxserver/unifi-controller
  #   container_name: unifi-controller
  #   environment:
  #     - PUID=${LOCAL_USER}
  #     - PGID=${LOCAL_USER}
  #   volumes:
  #     - /home/homeassistant/unifi/config:/config
  #   ports:
  #     - 3478:3478/udp
  #     - 10001:10001/udp
  #     - 8080:8080
  #     - 8443:8443
  #     - 1900:1900/udp
  #     - 8843:8843
  #     - 8880:8880
  #     - 6789:6789
  #     - 5514:5514
  #   restart: unless-stopped

  # vscode:
  #     image: linuxserver/code-server
  #     container_name: vscode
  #     hostname: vscode
  #     restart: always
  #     network_mode: bridge
  #     ports:
  #       - 8553:8443
  #     environment:
  #       PUID: ${LOCAL_USER}
  #       PGID: ${LOCAL_USER}
  #       TZ: "Asia/Jerusalem"
  #       # PASSWORD: ${VSCODE_PASSWORD} #optional
  #       # SUDO_PASSWORD: password #optional
  #     volumes:
  #       - /home/homeassistant/vscode/config:/config
