---
version: '3.6'

services:
  homeassistant:
    hostname: homeassistant
    network_mode: host
    container_name: "homeassistant"
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - ./homeassistant/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/dbus:/run/dbus:ro
    restart: always

  esphome:
    container_name: "esphome"
    image: ghcr.io/esphome/esphome
    network_mode: host
    environment:
      - TZ=Asia/Jerusalem
      - ESPHOME_DASHBOARD_USE_PING=true
    restart: unless-stopped
    volumes:
      - ./esphome/config:/config

  mqtt:
    image: library/eclipse-mosquitto:latest
    restart: unless-stopped
    volumes:
      - ./mosquitto/config/:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  whisper:
    container_name: whisper
    image: rhasspy/wyoming-whisper
    command: --model tiny-int8 --language he
    volumes:
      - ./assist/whisper/whisper-data:/data
    environment:
      - TZ=Asia/Jerusalem
    restart: unless-stopped
    ports:
      - 10300:10300
  oww:
    container_name: openWakeWord
    image: rhasspy/wyoming-openwakeword
    volumes:
      - ./assist/openWakeWord/data:/data
    environment:
      - TZ=Asia/Jerusalem
    restart: unless-stopped
    ports:
      - 10400:10400

  zigbee2mqtt:
    container_name: "z2m"
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt/:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Jerusalem
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0

  unifi-db:
    image: docker.io/mongo:4.4
    container_name: "unifi-db"
    volumes:
      - ./unifi-controller/mongodb/dbcfg:/data/configdb
      - ./unifi-controller/mongodb/:/data/db
      - ./unifi-controller/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command:
      mongod --port 27017
    restart: unless-stopped

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: "unifi-network-application"
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_USER=unifi
      - MONGO_PASS=unifipwd
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMI=1024
      - MEM_STARTUP=1024
    volumes:
      - ./unifi-controller/:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped
