---

- platform: group
  name: "All lights"
  entities:
    - light.yeelight_color_master_bedroom
    - light.yeelight_color_living_room_1
    - light.yeelight_color_living_room_2

- platform: group
  name: "Ceiling lights"
  entities:
    - light.yeelight_color_master_bedroom
    - light.yeelight_color_living_room_1
    - light.yeelight_color_living_room_2

- platform: group
  name: "Dining lights"
  entities:
    - light.yeelight_color_living_room_1
    - light.yeelight_color_living_room_2

- platform: group
  name: "Living room lights"
  entities:
    - light.yeelight_color_living_room_1
    - light.yeelight_color_living_room_2

- platform: group
  name: "Public lights"
  entities:
    - light.yeelight_color_living_room_1
    - light.yeelight_color_living_room_2

- platform: group
  name: "Room lights"
  entities:
    - light.yeelight_color_master_bedroom
