---

- alias: "Update IMS sensor"
  id: 8092fd00-4f2b-46cb-9855-5adde0e310c9
  trigger:
    - platform: time_pattern
      hours: "/1"
    - platform: homeassistant
      event: start
  action:
    service: pyscript.ims_sensor
