---

- alias: "Waze - update static sensors"
  id: b420b709-45ee-42f0-9fde-be4da53dc4f9
  trigger:
    platform: time_pattern
    minutes: /2
  condition:
    - condition: time
      after: '07:30:00'
      before: '09:00:00'
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    service: homeassistant.update_entity
    target:
      entity_id: sensor.tohar_from_home_to_work

- alias: "Waze - update dynamic sensors"
  id: b420b709-45ee-42f0-9fde-be4da53dc4f9
  trigger:
    platform: time_pattern
    minutes: /2
  condition:
    - condition: time
      after: '07:00:00'
      before: '23:59:00'
  action:
    - choose:
      - conditions:
          - "{{ is_state('person.tohar', 'not_home') }}"
        sequence:
          - service: homeassistant.update_entity
            target:
              entity_id: sensor.tohar_current_location_to_home
      - conditions:
          - "{{ is_state('person.yuval', 'not_home') }}"
        sequence:
          - service: homeassistant.update_entity
            target:
              entity_id: sensor.yuval_current_location_to_home
