---

- alias: "Start Dishwasher at shabbat afternoon"
  id: 3dcfc7f1-ee04-403f-b6a2-0ed67af48336
  trigger:
    trigger: time
    at: '15:00:00'
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
    - "{{ is_state('group.person', 'home') }}"
    - "{{ not is_state_attr('sensor.jewish_calendar_holiday', 'id', 'yom_kippur') }}"
  action:
    - action: switch.turn_on
      entity_id: switch.400090386855001425_bsh_common_setting_powerstate
    - delay: 2
    - action: button.press
      entity_id: button.400090386855001425_start_pause
