---

- alias: "Plate - Shabbat enter"
  description: >-
    "Precoution for Shabbat after Chag,
     Turn-on the plate if it's off,
     If its on it dosn't matter"
  id: 175ea9fb-d7b6-419f-992d-a7cea43a7420
  trigger:
    platform: sun
    event: sunset
  condition:
    - condition: time
      weekday:
        - fri
    - "{{ not is_state('input_boolean.out_for_shabbat_eve', 'on') }}"
  action:
    action: switch.turn_on
    data:
      entity_id: switch.shabbat_plate

- alias: "Plate - Turn-off plate at Shabbat noon"
  id: 48acb771-25fe-4629-9ce7-77dfc35adeab
  trigger:
    platform: time
    at: '13:30:00'
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
    - "{{ not is_state_attr('sensor.jewish_calendar_holiday', 'type_id', 1) }}"
  action:
    action: switch.turn_off
    data:
      entity_id: switch.shabbat_plate

- alias: "Plate - Seuda-Shlishit"
  id: eec856fd-3958-4296-984a-c62458c75c97
  trigger:
    platform: sun
    event: sunset
    offset: '-02:00:00'
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    action: switch.turn_on
    data:
      entity_id: switch.shabbat_plate

- alias: "Plate - Shabbat/Chag ends"
  id: 0cb6679a-5286-419e-95be-fe5c2850a247
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'off'
  action:
    action: switch.turn_off
    data:
      entity_id: switch.shabbat_plate

- alias: "Plate - Out for Shabbat morning"
  id: affe0510-ec83-4794-b7e7-69f7be51ce63
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition:
    - "{{ is_state('input_boolean.out_for_shabbat_morning', 'on') }}"
  action:
    action: switch.turn_off
    data:
      entity_id:
        - switch.shabbat_plate
        - input_boolean.out_for_shabbat_morning

- alias: "Plate - Out for Shabbat eve"
  id: 2e260c86-7c46-4bbb-8190-557c9d66cc8c
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - "{{ is_state('input_boolean.out_for_shabbat_eve', 'on') }}"
  action:
    - action: switch.turn_on
      data:
        entity_id: switch.shabbat_plate
    - action: switch.turn_off
      data:
        entity_id: input_boolean.out_for_shabbat_eve

#############################
#### Holiday automations ####
#############################

- alias: "Plate - Chag morning operation"
  # Will get turned off later by "Shabbat noon" automation
  id: 6a09b0cc-64f7-4cae-8d02-14ae61fe37fc
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    action: switch.turn_on
    data:
      entity_id: switch.shabbat_plate

- alias: "Plate - Turn-off plate at chag night"
  id: 2195b710-0c3a-4c4f-8a6a-961495f470a6
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - sat
    - "{{ not is_state('input_datetime.shabbat_lights_off_time', '00:00:00') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    action: switch.turn_off
    data:
      entity_id: switch.shabbat_plate
