---

- alias: "Climate - Turn-off Living-room climate at night"
  id: 5f250d83-aa9a-4e2a-af61-8ad83f39a75a
  trigger:
    platform: time
    at: '21:00:00'
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    service: climate.turn_off
    data:
      entity_id: climate.living_room

- alias: "Climate - Turn-off when door is open"
  id: 3e15ca2c-43bc-469e-958a-ce74bfb07502
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_window_contact
    to: 'on'
    for:
      minutes: 5
  condition:
    - "{{ not is_state('climate.living_room', 'off') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    service: climate.turn_off
    data:
      entity_id: climate.living_room
