---

- sensor:
  - name: "Master Bedroom sensibo Humidity"
    unique_id: 1a823d2f-3cd6-4213-a3b9-457014fccb47
    unit_of_measurement: '%'
    state: >-
      {{ state_attr('climate.shynh', 'current_humidity') }}
    icon: mdi:water-percent

  - name: "Master Bedroom sensibo temperature"
    unique_id: e25b54bb-e9e3-4822-96a2-17d30d7a906b
    unit_of_measurement: '°C'
    state: >-
      {{ state_attr('climate.shynh', 'current_temperature') }}
    icon: mdi:thermometer

  - name: "Living Room Set Temperature"
    unique_id: 6369a3bc-b9de-4e67-9d83-98432562cefb
    unit_of_measurement: '°C'
    state: >-
      {{ state_attr('climate.slvn', 'temperature') }}
    icon: mdi:home-thermometer-outline

  - name: "Master Bedroom Set Temperature"
    unique_id: b35b26e8-e2b1-4291-b2de-cc65b0edb9c6
    unit_of_measurement: '°C'
    state: >-
      {{ state_attr('climate.shynh', 'temperature') }}
    icon: mdi:home-thermometer-outline
