---

- binary_sensor:
  - name: "Tzom"
    # Does not return true on Kippur as it is a Holiday
    unique_id: a184d22d-221a-45e3-8065-e4c824d2b959
    state: >-
      {{ is_state_attr('sensor.jewish_calendar_holiday', 'type_id', 5) }}
    icon: >-
      {{ 'mdi:food-off' if is_state('binary_sensor.tzom', 'on') else 'mdi:food' }}
