---

- binary_sensor:
  # - name: "Master Bedroom Light is on"
  #   unique_id: a5668654-09f1-471c-b5eb-a142ce81cc3a
  #   state: >-
  #     {{ is_state('light.yeelight_color_master_bedroom', 'on') }}
  #   icon: >-
  #     {{
  #       'mdi:lightbulb-group' if is_state('binary_sensor.master_bedroom_light_is_on', 'on') else 'mdi:lightbulb-group-off'
  #     }}

  - name: "Living Room Lights is on"
    unique_id: b9d4c3c9-04d5-4df8-a49c-5828d1b070ce
    state: >-
      {{ is_state('light.living_room_lights', 'on') }}
    icon: >-
      {{
        'mdi:lightbulb-group' if is_state('binary_sensor.living_room_lights_is_on', 'on') else 'mdi:lightbulb-group-off'
      }}

  - name: "Bathroom Light is on"
    unique_id: 369c23bc-90a8-4a79-a218-33277c4adec6
    state: >-
      {{ is_state('light.bathroom_light', 'on') }}
    icon: >-
      {{
        'mdi:lightbulb' if is_state('binary_sensor.bathroom_light_is_on', 'on') else 'mdi:lightbulb-off'
      }}

  - name: "Corridor Light is on"
    unique_id: a9f6d18c-7441-4721-8a17-b01a1e886fee
    state: >-
      {{ is_state('light.corridor_light', 'on') }}
    icon: >-
      {{
        'mdi:lightbulb' if is_state('binary_sensor.corridor_light_is_on', 'on') else 'mdi:lightbulb-off'
      }}
