---

- trigger:
    - platform: state
      entity_id:
        - sensor.living_room_illuminance
        - weather.openweathermap
  sensor:
  - name: "Line dry"
    unique_id: b34a6e8a-fe25-4cf8-b637-8d1e79f611ce
    unit_of_measurement: 'minutes'
    state: >-
      {% if states('sensor.living_room_illuminance') | float == 0 %}
        unknown
      {% else %}
        {% set weather_entity = 'weather.openweathermap' %}
        {% set sunshine_percent = states('sensor.living_room_illuminance') | float / 6000 %}

        {% set temp = ((state_attr('weather_entity', 'temperature') | int) - 32) * 5 / 9 + 273 %}
        {% set wind = (state_attr('weather_entity', 'wind_speed') | float) / 2.237 %}
        {% set humidity = state_attr('weather_entity', 'humidity') | float / 100 %}
        {% set pressure = state_attr('weather_entity', 'pressure') | float * 33.86389 / 10 %}
        {% set rn = 9.4 * sunshine_percent %}

        {% set delta = ((5336 / temp) ** (21.07 - (5336 / temp))) %}
        {% set lamda = 2.501 - 0.002361 * (temp - 273) %}
        {% set y = (0.0016286 * pressure) / lamda %}
        {% set ea = 1 ** (21.07 - (5336 / temp)) %}
        {% set d = (1 - humidity) * ea %}
        {% set e = (delta * rn + y * (6.43 * (1 + 0.536 * wind) * d)) / (lamda * (delta + y)) %}

        {{ ((0.2 / (e)) * 1440) | int }}
      {% endif %}
