---

- sensor:
  - name: "Media Playing"
    unique_id: af956ef6-79b2-474b-a05f-df5d67fa2ce5
    state: >-
      {{ state_attr('media_player.tv', 'app_name') }}
    icon: >-
          {% set app = state_attr('media_player.tv', 'app_name') %}
          {% if app == 'Netflix' %}
            mdi:netflix
          {% elif app == 'com.disneyplus.mea' %}
            mdi:castle
          {% endif %}
