---

# Android devices report the alarm by the time it will fire a notification about upcoming alarm
# It is usually 30 to 10 minutes before the actual alarm will trigger
# the sensors below compansate for it and returning the correct value
# you can change the value below to the correct offset of your device
- sensor:
  - name: 'Tohar next Alarm formatted'
    unique_id: 14481c1c-eb67-43e7-b18f-50a0b4b6670b
    state: >-
      {{
        ((as_timestamp(states('sensor.tohar_next_alarm') | default(0)) | int + (15*60)) | timestamp_custom('%H:%M'))
      }}
    icon: mdi:alarm

  - name: 'Yuval next Alarm formatted'
    unique_id: fb411bbe-19e9-474d-acda-0343f08099e8
    state: >-
      {{
        ((as_timestamp(states('sensor.yuval_next_alarm') | default(0)) | int + (15*60)) | timestamp_custom('%H:%M'))
      }}
    icon: mdi:alarm
