---

- sensor:
  - name: "Living room temperature"
    unique_id: 8347de3b-0607-493b-8088-8e14f5ccee37
    state: >-
      {{ state_attr('climate.living_room', 'current_temperature') | float(default=0.0) }}
    unit_of_measurement: '°C'
  - name: "Living room humidity"
    unique_id: 0b248940-9fb7-48d9-bb07-c7a0713550d4
    state: >-
      {{ state_attr('climate.living_room', 'current_humidity') | float(default=0.0) }}
    unit_of_measurement: '%'

  - name: "Living room set temp"
    unique_id: 806d1cef-b238-4754-bb40-49af6e5c540f
    state: >-
      {{ state_attr('climate.living_room', 'temperature') | int(default=0) }}
    unit_of_measurement: '°C'

- binary_sensor:
  - name: "AC is on"
    unique_id: 3aa3dbdd-b082-4cb5-a02c-743c1debf27a
    state: >-
      {{ not is_state('climate.living_room', 'off') }}
