---

- sensor:
  - name: "Living room set temp"
    unique_id: 806d1cef-b238-4754-bb40-49af6e5c540f
    state: "{{ state_attr('climate.living_room', 'temperature') | int(default=0) }}"
    unit_of_measurement: '°C'
    icon: mdi:thermometer

- binary_sensor:
  - name: "AC"
    unique_id: 3aa3dbdd-b082-4cb5-a02c-743c1debf27a
    state: "{{ not is_state('climate.living_room', ['off', 'unknown']) }}"
