---

- sensor:
  - name: "Warmer or colder outside"
    unique_id: 8c57f5ee-d766-49d5-8121-5604d704481c
    state: >-
      {{
        'Cooler outside'
        if
        states('sensor.openweathermap_temperature') < states('sensor.living_room_temperature')
        else
        'Warmer outside'
      }}
    icon: >-
      {{
        'mdi:thermometer-chevron-up'
        if
        states('sensor.openweathermap_temperature') < states('sensor.living_room_temperature')
        else
        'mdi:thermometer-chevron-down'
      }}
    attributes:
      temperature_difference: >-
        {{
          (
            states('sensor.openweathermap_temperature') | float(default=0.0)
            -
            states('sensor.living_room_temperature') | float(default=0.0)
          ) | round(2)
        }}
