
---

- sensor:
  - name: "Yuval - time at work formatted"
    unique_id: 7b6420cc-087e-4296-8709-6c5c61fd6a6d
    unit_of_measurement: "hours"
    state_class: total
    state: >-
      {% set hours = states('sensor.yuval_time_at_work') | float(default=0.0) %}
      {% set minutes = ((hours % 1) * 60) | int(default=0) %}
      {% set hours = (hours - (hours % 1)) | int(default=0) %}
      {{ float('%02i.%02i'%(hours, minutes)) }}

  - name: "Yuval - time at IDF formatted"
    unique_id: e4808838-46aa-43d0-abaa-00ced5f3f0b2
    unit_of_measurement: "hours"
    state_class: total
    state: >-
      {% set hours = states('sensor.yuval_time_at_idf') | float(default=0.0) %}
      {% set minutes = ((hours % 1) * 60) | int(default=0) %}
      {% set hours = (hours - (hours % 1)) | int(default=0) %}
      {{ float('%02i.%02i'%(hours, minutes)) }}

  - name: "Tohar - time at work formatted"
    unique_id: db265de4-9927-4284-bfa3-ea981a19f7f6
    unit_of_measurement: "hours"
    state_class: total
    state: >-
      {% set hours = states('sensor.tohar_time_at_work') | float(default=0.0) %}
      {% set minutes = ((hours % 1) * 60) | int(default=0) %}
      {% set hours = (hours - (hours % 1)) | int(default=0) %}
      {{ float('%02i.%02i'%(hours, minutes)) }}

  - name: "Tohar - time at gym formatted"
    unique_id: a4589b8e-750d-4b19-bb2b-019a24cc5f7d
    unit_of_measurement: "hours"
    state_class: total
    state: >-
      {% set hours = states('sensor.tohar_time_at_gym') | float(default=0.0) %}
      {% set minutes = ((hours % 1) * 60) | int(default=0) %}
      {% set hours = (hours - (hours % 1)) | int(default=0) %}
      {{ float('%02i.%02i'%(hours, minutes)) }}
