---

- sensor:
  - name: "UV index (friendly)"
    unique_id: 4640e04d-aeee-43ea-8308-374dede093c7
    state: >-
      {% set index = (states('sensor.current_uv_index')) | int %}
      {% if index >= 11 %}
        Dangerous
      {% elif index >= 8 %}
        High risk
      {% elif index >= 6 %}
        Sunburn
      {% elif index >= 3 %}
        Sunglasses
      {% elif index >= 1 %}
        No risk
      {% elif index >= 0 %}
        No UV radiation
      {% elif index < 0 %}
        unknown
      {% endif %}
    icon: >-
      {% set index = (states('sensor.current_uv_index')) | int %}
      {% if index >= 11 %}
        mdi:close-octagon
      {% elif index >= 8 %}
        mdi:alert
      {% elif index >= 6 %}
        mdi:shield-sun
      {% elif index >= 3 %}
        mdi:sunglasses
      {% elif index >= 0 %}
        mdi:check-bold
      {% elif index < 0 %}
        mdi:eye
      {% endif %}
    attributes:
      color: >-
        {% set index = (states('sensor.current_uv_index')) | int %}
        {% if index >= 11 %}
          #E90E69
        {% elif index >= 8 %}
          #F90F10
        {% elif index >= 6 %}
          #FBA404
        {% elif index >= 3 %}
          #FCFB05
        {% elif index >= 0 %}
          #B8EC13
        {% elif index < 0 %}
          None
        {% endif %}
