---

- sensor:
  - name: "Vacuum Fan speed"
    unique_id: c5efde29-c48f-4faa-9363-9c514204bb60
    state: >-
      {% set speed = state_attr('vacuum.roborock_s7', 'fan_speed') if states('vacuum.roborock_s7') else "unknown" %}
      {% if speed == 'off' %}
        Off
      {% elif speed == 'quiet' %}  custom
        Quiet
      {% elif speed == 'balanced' %}
        Balanced
      {% elif speed == 'turbo' %}
        Turbo
      {% elif speed == 'max' %}
        Max
      {% elif speed == 'custom' %}
        Custom
      {% endif %}
    icon: >-
      {% set speed = state_attr('vacuum.roborock_s7', 'fan_speed') if states('vacuum.roborock_s7') else "unknown" %}
      {% if speed == 'off' %}
        mdi:fan-off
      {% elif speed == 'quiet' %}
        mdi:fan-speed-1
      {% elif speed == 'balanced' %}
        mdi:fan-speed-2
      {% elif speed == 'turbo' %}
        mdi:fan-speed-3
      {% elif speed == 'max' %}
        mdi:weather-tornado
      {% else %}
        mdi:alert-circle
      {% endif %}
