---

- sensor:
  - name: "Aqara button 1 linkquality percent"
    unique_id: 843110c2-96d0-43be-bfb6-e70920b465ec
    unit_of_measurement: "%"
    state: >-
      {{ ((states('sensor.aqara_button_1_linkquality') | int(0) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.aqara_button_1_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Aqara button 2 linkquality percent"
    unique_id: ffe1dc41-fd3b-4503-9470-6bf69c6af942
    unit_of_measurement: "%"
    state: >-
      {{ ((states('sensor.aqara_button_2_linkquality') | int(0) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.aqara_button_2_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Living room window linkquality percent"
    unique_id: a0b7a1bd-a457-45d6-85fe-8463a26d8205
    unit_of_measurement: "%"
    state: >-
      {{ ((states('sensor.living_room_window_linkquality') | int(0) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.living_room_window_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Bathroom door linkquality percent"
    unique_id: 1bd3b357-a7d5-4908-851d-4f4efbf87075
    unit_of_measurement: "%"
    state: >-
      {{ ((states('sensor.bathroom_door_linkquality') | int(0) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.bathroom_door_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Ensuite door linkquality percent"
    unique_id: 1005f3f6-7c23-44ef-a164-31a9d657cd41
    unit_of_measurement: "%"
    state: >-
      {{ ((states('sensor.ensuite_door_linkquality') | int(0) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.ensuite_door_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}
