---

- sensor:
  - name: "Master bedroom button linkquality percent"
    unique_id: 843110c2-96d0-43be-bfb6-e70920b465ec
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.master_bedroom_button_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.master_bedroom_button_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Living room button linkquality percent"
    unique_id: f33f1fa2-d86d-49b5-8b85-e9a48bb6bf03
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.living_room_button_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.living_room_button_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Living room window linkquality percent"
    unique_id: a0b7a1bd-a457-45d6-85fe-8463a26d8205
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.living_room_window_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.living_room_window_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Bathroom door linkquality percent"
    unique_id: 1bd3b357-a7d5-4908-851d-4f4efbf87075
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.bathroom_door_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.bathroom_door_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Ensuite door linkquality percent"
    unique_id: 1005f3f6-7c23-44ef-a164-31a9d657cd41
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.ensuite_door_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.ensuite_door_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Master bedroom door linkquality percent"
    unique_id: 1c4d4000-84b3-456a-80de-400ff02e0101
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.master_bedroom_door_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.master_bedroom_door_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Master bedroom H&T linkquality percent"
    unique_id: a01137aa-db54-46c5-928e-a84d3e14f39e
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.master_bedroom_h_t_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.master_bedroom_h_t_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Living room H&T linkquality percent"
    unique_id: e8a2ba26-bff6-430a-947b-389a47bfaf5b
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.living_room_h_t_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.living_room_h_t_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Kids bedroom H&T linkquality percent"
    unique_id: c5ea099d-5a6c-4bb5-bf83-c5dd786968f4
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.kids_bedroom_h_t_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.kids_bedroom_h_t_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}

  - name: "Outdoor H&T linkquality percent"
    unique_id: 3799b0c4-a35d-475d-833a-a8b2ddcdae46
    unit_of_measurement: "%"
    state_class: measurement
    state: >-
      {{ ((states('sensor.outdoor_h_t_linkquality') | int(default=1) / 255) * 100) | round (1) }}
    icon: >-
      {% set lqi = states('sensor.outdoor_h_t_linkquality_percent') %}
      {% if lqi <= '35' %}
        mdi:signal-cellular-1
      {% elif lqi <= '65' %}
        mdi:signal-cellular-2
      {% elif lqi <= '100' %}
        mdi:signal-cellular-3
      {% else %}
        mdi:signal-off
      {% endif %}
