remote_start:
  name: Remote Start
  description: Send to ThinQ device the remote start command.
  target:
    entity:
      integration: smartthinq_sensors
      domain: sensor

wake_up:
  name: WakeUp
  description: Send to ThinQ device the wakeup command.
  target:
    entity:
      integration: smartthinq_sensors
      domain: sensor
