---

- alias: "Climate - Turn on Living-room climate when Shabbat enter"
  id: eb10652e-6276-4c18-b063-d14fc7c2d2cb
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - condition: numeric_state
      entity_id: sensor.living_room_temperature
      above: 25
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.living_room
    - delay: 2
    - service: climate.set_temperature
      data:
        temperature: 23
        hvac_mode: cool
      target:
        entity_id: climate.living_room

- alias: "Climate - Turn off Living-room climate at Shabbat night"
  id: c7396673-d257-4267-a72f-060ee4d43603
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.living_room

- alias: "Climate - Turn on Living-room climate at Shabbat"
  id: 04e461f4-456c-4b75-a193-a8b9b64b32ac
  trigger:
    platform: time
    at:
      - '14:00:00'
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.living_room
    - delay: 2
    - service: climate.set_temperature
      data:
        temperature: 23
        hvac_mode: cool
      target:
        entity_id: climate.living_room
