---

- alias: "Climate - Turn on Living-room climate when Shabbat enter"
  id: eb10652e-6276-4c18-b063-d14fc7c2d2cb
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - condition: numeric_state
      entity_id: sensor.living_room_temperature
      above: 24
  action:
    service: script.turn_on
    data:
      entity_id: script.ac_cool

- alias: "Climate - Turn off Living-room climate at Shabbat night"
  id: c7396673-d257-4267-a72f-060ee4d43603
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    service: climate.turn_off
    data:
      entity_id: climate.living_room

- alias: "Climate - Turn on when door is closed"
  id: fe96ab5c-d38d-4617-9032-59f481ef98aa
  trigger:
    platform: time_pattern
    minutes: 5
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
    - condition: time
      after: '08:00:00'
      before: input_datetime.shabbat_lights_off_time
    - "{{ is_state('binary_sensor.living_room_window_contact', 'off') }}"
    - "{{ is_state('climate.living_room', 'off') }}"
    - "{{ is_state('group.person', 'home') }}"
  action:
    service: script.turn_on
    data:
      entity_id: script.ac_cool

- alias: "Climate - Shabbat Night climate"
  id: 8f583c89-8cfa-4aba-be92-cc98d727dcf2
  trigger:
    platform: time_pattern
    minutes: 30
  condition:
    - condition: time
      after: '01:00:00'
      before: '07:00:00'
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
    - "{{ is_state('group.person', 'home') }}"
  action:
    - if:
        condition: state
        entity_id: climate.living_room
        state: 'off'
      then:
        service: script.turn_on
        data:
          entity_id: script.ac_cool
      else:
        service: climate.turn_off
        data:
          entity_id: climate.living_room
