---

- alias: "Climate - Turn on Living-room climate when Shabbat enter"
  id: eb10652e-6276-4c18-b063-d14fc7c2d2cb
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - condition: numeric_state
      entity_id: sensor.living_room_temperature
      above: 25
  action:
    - service: script.turn_on
      data:
        entity_id: script.ac_cool

- alias: "Climate - Turn off Living-room climate at Shabbat night"
  id: c7396673-d257-4267-a72f-060ee4d43603
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    - service: climate.turn_off
      data:
        entity_id: climate.living_room

- alias: "Climate - Turn on Living-room climate at Shabbat"
  id: 04e461f4-456c-4b75-a193-a8b9b64b32ac
  trigger:
    platform: time
    at:
      - '14:00:00'
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    - service: script.turn_on
      data:
        entity_id: script.ac_cool

- alias: "Climate - Turn on when door is closed"
  id: fe96ab5c-d38d-4617-9032-59f481ef98aa
  trigger:
    platform: time_pattern
    minutes: 5
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
    - condition: time
      after: '14:00:00'
    - "{{ is_state('binary_sensor.random_boolean', 'on')}}"
    - "{{ is_state('binary_sensor.living_room_window_contact', 'off')}}"
    - "{{ is_state('climate.living_room', 'off')}}"
  action:
    - service: script.turn_on
      data:
        entity_id: script.ac_cool
