---

- alias: "Climate - Turn off Living-room climate at night"
  id: 5f250d83-aa9a-4e2a-af61-8ad83f39a75a
  trigger:
    platform: time
    at: '21:00:00'
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    service: climate.turn_off
    data:
      entity_id:
        - climate.living_room_cool_thermostat
        - climate.slvn

- alias: "Climate - Turn off when away"
  id: ae0c5bd5-96f8-4cde-ba22-9d46167c1a6b
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  condition: "{{ is_state('input_boolean.guest_mode', 'off') }}"
  action:
    service: climate.turn_off
    data:
      entity_id:
        - climate.living_room_cool_thermostat
        - climate.slvn

- alias: "Climate - Turn off when away - master bedroom"
  id: d7a2e86c-2519-4396-870a-e7d979cf516a
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  condition: "{{ not is_state('climate.shynh', 'off') }}"
  action:
    service: climate.turn_off
    data:
      entity_id: climate.shynh
