---

- alias: "Climate - Turn off Ensuite heater when reaching time or temp"
  id: bb829a6e-f2ce-4d09-b7e4-312f8ddd7a89
  trigger:
    - platform: state
      entity_id: switch.ensuite_heater
      to: 'on'
      for: '00:25:00'
    - platform: numeric_state
      entity_id: sensor.ensuite_temperature
      above: 21
  action:
    service: switch.turn_off
    data:
      entity_id: switch.ensuite_heater
