---

- alias: "Toggle sheet heaters"
  description: >-
    "This automation turns on the sheet heaters at 6:30 PM if someone is home,
    and turns them off later that night."
  id: bbd85c59-0fd0-441c-8404-7ca7b6e3fc85
  trigger:
    - trigger: time
      at: '18:30:00'
      id: 'on'
    - trigger: time
      at: '23:00:00'
      id: 'off'
  action:
    choose:
      - conditions:
        - condition: trigger
          id: 'on'
        - "{{ is_state('group.person', 'home') }}"
        sequence:
          action: switch.turn_on
          data:
            entity_id: switch.kids_socket
      - conditions:
        - condition: trigger
          id: 'off'
        sequence:
          action: switch.turn_off
          data:
            entity_id: switch.kids_socket
