---

- alias: "Climate - Turn on Living-room climate when Shabbat enter"
  id: eb10652e-6276-4c18-b063-d14fc7c2d2cb
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  condition: "{{ is_state('group.person', 'home') }}"
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.living_room_cool_thermostat
    - delay: 2
    - service: climate.set_temperature
      data:
        temperature: 24
        hvac_mode: cool
      target:
        entity_id: climate.slvn

- alias: "Climate - Turn off Living-room climate at Shabbat night"
  id: c7396673-d257-4267-a72f-060ee4d43603
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    - service: climate.turn_off
      data:
        entity_id:
          - climate.living_room_cool_thermostat
          - climate.slvn
    - delay: 10
    # Repeat once more becouse I can't trust sensibo
    - service: climate.turn_off
      data:
        entity_id:
          - climate.living_room_cool_thermostat
          - climate.slvn

- alias: "Climate - Turn on Living-room climate at Shabbat"
  id: 04e461f4-456c-4b75-a193-a8b9b64b32ac
  trigger:
    platform: time
    at:
      - '08:00:00'
      - '14:00:00'
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    - service: climate.turn_on
      data:
        entity_id: climate.living_room_cool_thermostat
    - delay: 2
    - service: climate.set_temperature
      data:
        temperature: 24
        hvac_mode: cool
      target:
        entity_id: climate.slvn

- alias: "Climate - Turn off Living-room climate at Shabbat noon"
  id: f570b89f-8ce5-4b09-9230-1acc55c54528
  trigger:
    platform: time
    at: '13:00:00'
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    service: climate.turn_off
    data:
      entity_id:
        - climate.living_room_cool_thermostat
        - climate.slvn
