---

doorbell:
  sequence:
    - service: script.turn_on
      data:
        entity_id:
          - script.doorbell_notification
          - script.doorbell_lights

doorbell_notification:
  sequence:
  - entity_id: camera.doorbell_camera
    service: camera.snapshot
    data:
      filename: '/config/www/cam_captures/doorbell/front_door_snapshot_latest.jpg'
  - service: notify.mobile_app_yuval_phone
    data:
      title: "Doorbell"
      message: Doorbell pressed at {{ as_timestamp(now()) | timestamp_custom('%-H:%M', true) }}
      data:
        actions:
        - action: doorbell_open
          title: "Open"
        - action: doorbell_no_entry
          title: "Nope"
        clickAction: /lovelace/ui-lovelace/doorbell
        image: '/local/cam_captures/doorbell/front_door_snapshot_latest.jpg'
        priority: high
        tag: doorbell
        ttl: 0

doorbell_lights:
  sequence:
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.living_room_lights
    - delay:
        milliseconds: 500
    - service: light.turn_off
      data:
        entity_id: light.living_room_lights
    - delay:
        milliseconds: 200
    - service: light.turn_on
      data:
        color_name: blue
        entity_id: light.living_room_lights
    - delay:
        milliseconds: 500
    - service: light.turn_on
      data:
        entity_id: light.living_room_lights
        brightness_pct: 100
        kelvin: 3000
