---

# Set Vacuum fan speed
######################
vacuum_set_silent:
  alias: "Set Silent"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
      fan_speed: 38

vacuum_set_standard:
  alias: "Set Standard"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
      fan_speed: 60

vacuum_set_turbo:
  alias: "Set Turbo"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
      fan_speed: 75

vacuum_set_max:
  alias: "Set Max"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
      fan_speed: 100

# Reset Consumables
###################
vacuum_reset_sensor:
  alias: "Reset cliff sensors"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.xiaomi_vacuum_cleaner
      params: sensor_dirty_time

vacuum_reset_filter:
  alias: "Reset Filter"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.xiaomi_vacuum_cleaner
      params: filter_work_time

vacuum_reset_side_brush:
  alias: "Reset side brush"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.xiaomi_vacuum_cleaner
      params: side_brush_work_time

vacuum_reset_main_brush:
  alias: "Reset main brush"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.xiaomi_vacuum_cleaner
      params: main_brush_work_time
