---

- name: "Shabbat end"
  icon: mdi:candle
  entities:
    switch.shabbat_mode:
      state: 'off'
    # light.room_lights:
    #   state: 'off'
    light.living_room_lights:
      state: 'on'
      brightness: 200
    # light.important_lights:
    #   state: 'off'
    # light.kids_ambient_lights:
    #   state: 'on'
    #   effect: 'Colortwinkles'
