---

- name: "Shabbat end"
  icon: mdi:candle
  entities:
    light.room_lights:
      state: 'off'
    light.living_room_lights:
      state: 'on'
      brightness_pct: 80
      kelvin: 3200
    light.importent_lights:
      state: 'off'
    switch.shabbat_mode:
      state: 'off'
