---

- name: "Shabbat eve"
  icon: mdi:candle
  entities:
    light.room_lights:
      state: 'off'
    light.living_room_lights:
      state: 'on'
      brightness_pct: 90
      kelvin: 3200
    light.importent_lights:
      state: 'on'
      brightness_pct: 70
      kelvin: 4000
    switch.shabbat_mode:
      state: 'on'
