---

- alias: "Dishwasher - start at shabbat afternoon"
  id: 3dcfc7f1-ee04-403f-b6a2-0ed67af48336
  trigger:
    platform: sun
    event: sunset
    offset: '-03:00:00'
  condition:
    - condition: time
      weekday:
        - sat
    - "{{ is_state('group.person', 'home') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.400090386855001425_bsh_common_setting_powerstate
    - delay: 2
    - service: button.press
      entity_id: button.400090386855001425_start_pause
