---

- platform: group
  name: "Public lights"
  entities:
    - light.kitchen_ceiling_light
    - light.living_room_ceiling_light
    - light.wall_light_right
    - light.wall_light_left
    - light.corridor_light
    - light.bathroom_light
