---

person:
  card:
    type: picture-elements
    image: '/local/assets/[[name]].jpg'
    elements:
      - type: state-label
        entity: sensor.[[name]]_battery_level
        style:
          top: 11%
          right: -2%
      - type: state-icon
        entity: sensor.[[name]]_battery_level
        style:
          top: 10%
          right: -10%
