---

room_multisensor:
  card:
    type: custom:room-card
    title: '[[room]]'
    entity: light.[[room]]_light
    tap_action:
      action: toggle
    icon: mdi:lightbulb-outline
    info_entities:
      - entity: binary_sensor.[[room]]_motion
        show_icon: true
      - entity: binary_sensor.[[room]]_door
        show_icon: true
        icon:
          state_on: mdi:door-open
          state_off: mdi:door-closed
      - sensor.[[room]]_illuminance
      - sensor.motion_sensor_temperature
    cards:
      - type: custom:decluttering-card
        template: env
        variables:
          - room: '[[room]]'
      - type: glance
        entities:
          - entity: sensor.[[room]]_thermal_comfort_perception
            name: "Comfort scale"
