---

- alias: "Plate - Start Chag timer"
  id: f6711174-7249-43d3-a70a-e1a9fa147ffe
  trigger:
    platform: state
    entity_id: binary_sensor.jewish_calendar_issur_melacha_in_effect
    to: 'on'
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
  action:
    - service: timer.start
      data:
        entity_id: timer.chag_eve_plate
    - service: switch.turn_on
      data:
        entity_id: switch.shabbat_plate

- alias: "Plate - Turn-off plate on chag eve"
  description: "We don't need the plate for the night in Chag"
  id: ab698dfc-9a41-4f15-bf63-cd95eaf95ee2
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.chag_eve_plate
  action:
    service: switch.turn_off
    data:
      entity_id: switch.shabbat_plate

- alias: "Plate - Chag morning operation"
  # Will get turned off later by "Shabbat noon" automation
  id: 6a09b0cc-64f7-4cae-8d02-14ae61fe37fc
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    service: switch.turn_on
    data:
      entity_id: switch.shabbat_plate

- alias: "Plate - Turn-off plate at chag night"
  id: 2195b710-0c3a-4c4f-8a6a-961495f470a6
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition:
    - condition: time
      weekday:
        - sat
    - "{{ not is_state('input_datetime.shabbat_lights_off_time', '00:00:00') }}"
  action:
    service: switch.turn_off
    data:
      entity_id: switch.shabbat_plate
