---

- platform: template
  sensors:
    is_fast_day:
      # Does not return true on Kippur as it is a Holiday
      friendly_name: "צום"
      value_template: >-
        {{ is_state_attr('sensor.jewish_calendar_holiday', 'type_id', 5) }}
      icon_template: >-
        {% if is_state('binary_sensor.is_fast_day', 'on') %}
          mdi:food-off
        {% else %}
          mdi:food
        {% endif %}
    is_omer:
      friendly_name: "עומר"
      value_template: >-
        {{ (states('sensor.jewish_calendar_day_of_the_omer') | int) > 0 }}
    issur_melacha_eve:
      friendly_name: "ערב שבת או חג"
      value_template: >-
        {{
          now().weekday() == 4
          or
          states('sensor.jewish_calendar_holiday') == '2'
        }}

# Shabbat notification triggers
# FIXME: These sensors have hardcoded timezone offset.
# // Help needed to fix this
# 10800s for +3hrs offset, 7200s for +2hrs offset.
- platform: template
  sensors:
    shabbat_notification_10m:
      friendly_name: "Shabbat 10 min Notification Trigger"
      value_template: >-
        {{
          as_timestamp(
            states('sensor.jewish_calendar_upcoming_candle_lighting')
          ) |
          timestamp_custom('%H:%M:%S') == (now().strftime("%s") |
          float + (10*60) - (10800) ) |
          timestamp_custom("%H:%M:%S")
        }}
    shabbat_notification_trigger_30m:
      friendly_name: "Shabbat Half hour Notification Trigger"
      value_template: >-
        {{
          as_timestamp(
            states('sensor.jewish_calendar_upcoming_candle_lighting')
          ) |
          timestamp_custom('%H:%M:%S') == (now().strftime("%s") |
          float + (30*60) - (10800) ) |
          timestamp_custom("%H:%M:%S")
        }}
