---

- platform: template
  sensors:
    red_alert:
      friendly_name: "RED ALERT"
      value_template: "{{ 'פתח תקווה' in states('sensor.pakar_alerts') }}"
      attribute_templates:
        locations: "{{ states('sensor.pakar_alerts') }}"
      icon_template: >-
        {% if is_state('binary_sensor.red_alert', 'on') %}
          mdi:alert
        {% else %}
          mdi:alert-outline
        {% endif %}
