---

exclude:
  entities:
    - sensor.israel_weather_forecast
    - sensor.myip
    - sensor.ims_daily
    - sensor.hacs
    - sensor.random_number
    - sensor.openweathermap_weather_code

    - binary_sensor.random_boolean
    - binary_sensor.day
    - binary_sensor.night
  entity_globs:
    - sensor.jewish_calendar_*
    - sensor.count_*
    - sensor.skin_type_*
    - sensor.openweathermap_forecast_*

    - binary_sensor.is_*
  domains:
    - camera
    - automation
    - sun
    - script
    - switch
    - timer
    - button
