---

purge_keep_days: 30
exclude:
  entities:
    - sensor.time
    - sensor.date
    - sensor.date_time
    - sensor.watchman_last_updated
  entity_globs:
    - binary_sensor.is_*
    - sensor.count_*
    - sensor.skin_type_*
    - sensor.openweathermap_forecast_*
    - persistant_notification.notification_*
  domains:
    - sun
    - timer
    - weather
    - button
    - media_player
