---

db_url: !secret postgres_addr
purge_keep_days: 30
exclude:
  entities:
    - sensor.time
    - sensor.date
    - sensor.date_time
    - sensor.season
    - sensor.israel_weather_forecast
    - sensor.myip
    - sensor.ims_daily
    - sensor.openweathermap_weather_code
    - sensor.random_number
    - sensor.hacs

    - binary_sensor.random_boolean
  entity_globs:
    - sensor.count_*
    - sensor.skin_type_*
    - sensor.openweathermap_forecast_*

    - binary_sensor.is_*
  domains:
    - sun
    - weather
    - updater
    - timer
