---

purge_keep_days: 30
exclude:
  entities:
    - binary_sensor.random_boolean
    - sensor.time
    - sensor.date
    - sensor.date_time
    - sensor.israel_weather_forecast
    - sensor.openweathermap_weather_code
    - sensor.random_number
    - sensor.watchman_last_updated
  entity_globs:
    - binary_sensor.is_*
    - sensor.count_*
    - sensor.skin_type_*
    - sensor.openweathermap_forecast_*
    - persistant_notification.notification_*
  domains:
    - sun
    - timer
    - weather
    - camera
    - button
