---

- alias: "Update presence for Yuval"
  id: b01797ff-3063-4fb7-bbfe-c4fb139ec66a
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.yuval_mi_band_3
  action:
    - service: device_tracker.see
      data:
        dev_id: "yuval"
        location_name: >
          {% if trigger.to_state.state == 'on' %}
            home
          {% elif trigger.to_state.state == 'off' %}
            not_home
          {% else %}
             unknown
          {% endif %}

- alias: "Update presence for Tohar"
  id: 4d77610f-31b3-4f03-bd3c-65bbab729d76
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.tohar_amazefit_gts
  action:
    - service: device_tracker.see
      data:
        dev_id: "tohar"
        location_name: >
          {% if trigger.to_state.state == 'on' %}
            home
          {% elif trigger.to_state.state == 'off' %}
            not_home
          {% else %}
             unknown
          {% endif %}
