---

- alias: "Zigbee - Disable join"
  id: 3bc14262-ab06-418f-a3c5-db29f12e3d6a
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee2mqtt_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: 'zigbee2mqtt/bridge/config/permit_join'
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id:
        - input_boolean.zigbee2mqtt_permit_join
