add_tracking:
  name: Add tracking
  description: Add new tracking number to aliexpress_package_tracker.
  fields:
    tracking_number:
      name: Tracking number
      description: Tracking number for the new tracking
      required: true
      example: "123456789"
      selector:
        text:
    title:
      name: Title
      description: A custom title for the new tracking
      example: "Laptop"
      selector:
        text:

remove_tracking:
  name: Remove tracking
  description: Remove a tracking number from aliexpress_package_tracker.
  fields:
    tracking_number:
      name: Tracking number
      description: Tracking number of the tracking to remove
      required: false
      example: "123456789"
      selector:
        text:
    entity_id:
      name: entity_id
      description: The ID of the entity to remove
      required: false
      selector:
        entity:
          multiple: true
          filter:
            - integration: "aliexpress_package_tracker"
              domain: sensor
edit_title:
  name: "Edit Title"
  description: "Change the title attribute of a specific AliExpress tracking entity."

  fields:
    entity_id:
      description: "The entity ID of the AliExpress tracking sensor."
      example: "sensor.aliexpress_order_12345"
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - integration: "aliexpress_package_tracker"
              domain: sensor
    new_title:
      description: "The new title to set for the entity."
      example: "My New Order Name"
      required: true
      selector:
        text: