---

- platform: ping
  host: !secret sensibo_living_room
  name: "Living room Sensibo"
  count: 2

- platform: ping
  host: sensor.master_bedroom_fan_ip
  name: "Fan"
  count: 2

- platform: ping
  host: sensor.shabbat_plate_ip
  name: "Shabbat Plate"
  count: 2
