---

- platform: ping
  host: !secret vacuum
  name: "Vacuum"
  count: 2
- platform: ping
  host: !secret laptop
  name: "Laptop"
  count: 2
- platform: ping
  host: !secret tv
  name: "TV"
  count: 2

# Sensibo
- platform: ping
  host: !secret sensibo_living_room
  name: "Living room Sensibo"
  count: 2
- platform: ping
  host: !secret sensibo_master_bedroom
  name: "Master bedroom Sensibo"
  count: 2

# WLED
- platform: ping
  host: !secret wled_master_bedroom
  name: "WLED Master bedroom"
  count: 2
