---

title: "Kids Room"
icon: mdi:bed-outline
cards:
  - type: entities
    show_header_toggle: false
    entities:
      - type: custom:hui-element
        card_type: light
        entity: light.kids_ambient_lights
      - type: custom:hui-element
        card_type: horizontal-stack
        cards:
          - type: entities
            entities:
              - type: custom:hui-element
                card_type: light
                entity: light.wled_harel_bed
              - type: custom:rgb-light-card
                entity: light.wled_harel_bed
                colors:
                  - rgb_color:
                        - 255
                        - 127
                        - 255
                    transition: 1
          - type: entities
            entities:
              - type: custom:hui-element
                card_type: light
                entity: light.wled_rotem_bed
              - type: custom:rgb-light-card
                entity: light.wled_rotem_bed
                colors:
                  - rgb_color:
                        - 255
                        - 127
                        - 255
                    transition: 1
