---

title: "Master Bedroom"
icon: mdi:bed-king-outline
cards:
#  - type: custom:decluttering-card
#    template: multisensor
#    variables:
#      - room: master_bedroom

  - type: entities
    show_header_toggle: false
    entities:
      - type: custom:hui-element
        card_type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.master_bedroom_sensibo_temperature
                name: "Temperature"
                show_points: false
              - entity: sensor.master_bedroom_climate_set_temp
                color: 'white'
                show_fill: false
              - !include ../resources/graph_card_sun_elevation.yaml
            font_size: 80
            color_thresholds: !include ../resources/graph_card_temperature_thresholds.yaml
            points_per_hour: 6
            show:
              fill: fade
              points: false
              labels: true
              labels_secondary: false
              legend: false
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.master_bedroom_sensibo_humidity
                name: "Humidity"
                color: '#74A4F4'
              - !include ../resources/graph_card_sun_elevation.yaml
            font_size: 80
            lower_bound: 0
            upper_bound: 100
            points_per_hour: 12
            show:
              fill: fade
              points: false
              labels: false
              legend: false

  - type: custom:simple-thermostat
    entity: climate.shynh
    step_size: 1
    name: false
    control:
      - hvac

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: light
        entity: light.yeelight_color_master_bedroom
      - type: custom:hui-element
        card_type: light
        entity: light.wled_master_bedroom

  - type: entities
    entities:
      - entity: media_player.tv_master_bedroom
      - type: custom:hui-element
        card_type: grid
        columns: 3
        cards:
          - type: 'custom:elapsed-time-card'
            format: Time Elapsed
            time_format: 1h 5m
            time_today: sensor.track_tv_watch_time
            name: "Television"
            icon: television
          - type: 'custom:elapsed-time-card'
            format: Time Elapsed
            time_format: 1h 5m
            time_today: sensor.track_netflix_watch_time
            name: "Netflix"
            icon: netflix
          - type: 'custom:elapsed-time-card'
            format: Time Elapsed
            time_format: 1h 5m
            time_today: sensor.track_youtube_watch_time
            name: "Youtube"
            icon: youtube

  - type: entities
    entities:
      - type: custom:battery-entity-row
        entity: sensor.yuval_battery_level
        name: "Yuval battery"
        charging: true
      - entity: sensor.yuval_next_alarm
        name: "Alarm"
      - type: divider
      - type: custom:battery-entity-row
        entity: sensor.tohar_battery_level
        name: "Tohar battery"
        charging: true
      - entity: sensor.tohar_next_alarm
        name: "Alarm"
