---

title: "Monitoring"
icon: mdi:counter
cards:
  - type: custom:animated-consumption-card
    entity: sensor.total_ac_power_consumption

  - type: custom:mini-graph-card
    name: "AC Power Consumption"
    unit: 'kW'
    hours_to_show: 750
    line_width: 1
    entities:
      - entity: sensor.total_ac_energy_usage_daily
        name: "Daily"
        color: '#04FC04'
        show_state: true
        show_points: false
      - entity: sensor.total_ac_energy_usage_weekly
        name: "Weekly"
        color: 'yellow'
        show_state: false
        show_points: false
      - entity: sensor.total_ac_energy_usage_monthly
        name: "Monthly"
        color: 'red'
        show_state: false
        show_points: false
    show:
      fill: fade

  - type: custom:mini-graph-card
    name: "Daily water consumption"
    hours_to_show: 750
    line_width: 1
    entities:
      - entity: sensor.water_meter_9926387_today_s_consumption
        name: "Daily"
        show_state: true
        show_points: false
