---

title: "System Monitor"
icon: mdi:server
cards:
  - type: glance
    title: "Components"
    columns: 4
    entities:
      - entity: sensor.count_entities
        name: "Entities"
      - entity: sensor.count_sensors
        name: "Sensors"
      - entity: sensor.count_binary_sensors
        name: "Binary Sensors"
      - entity: sensor.count_switches
        name: "Switches"
      - entity: sensor.count_lights
        name: "Lights"
      - entity: sensor.count_automations
        name: "Automations"
        tap_action:
          action: call-service
          service: automation.reload
      - entity: sensor.count_scripts
        name: "Scripts"
        tap_action:
          action: call-service
          service: script.reload
      - entity: sensor.count_device_trackers
        name: "Device Trackers"
      - entity: sensor.count_input_boolean_entities
        name: "Input Booleans"
        tap_action:
          action: call-service
          service: input_boolean.reload
      - entity: sensor.count_input_select_entities
        name: "Input Select"
        tap_action:
          action: call-service
          service: input_select.reload
      - entity: sensor.count_input_datetime_entities
        name: "Input Date Times"
        tap_action:
          action: call-service
          service: input_datetime.reload
      - entity: sensor.count_timers
        name: "Timers"
        tap_action:
          action: call-service
          service: timer.reload
      - entity: sensor.count_climates
        name: "Climate"

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: picture-entity
        image: 'https://repository-images.githubusercontent.com/12888993/0f9eb780-655b-11e9-85cb-0d3956096fe5'
        entity: sensor.current_version
      - entity: sensor.uptime
      - entity: script.homeassistant_restart
        icon: mdi:restart
      - type: custom:hui-element
        card_type: custom:mini-graph-card
        icon: mdi:database
        entities:
          - entity: sensor.db_size
            name: "Database"
        show:
          fill: fade
          points: false
      - type: custom:hui-element
        card_type: entities
        entities:
          - script.reload_cli_sensors
          - script.reload_thermostats
          - script.reload_history_stats
          - script.reload_persons
          - script.reload_ping_sensors
          - script.reload_pyscript
          - script.reload_templates
          - script.reload_themes

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: picture-entity
        image: 'https://cdn.27.ua/main/14e/eaton_logo_mobile.png.pagespeed.ce.b32eoh_8jo.png'
        entity: sensor.ups_status
      - type: custom:battery-entity-row
        entity: sensor.ups_battery_charge
        name: "Battery Charge"
      - sensor.ups_time_remaining
      - sensor.ups_load_watts
      - type: custom:bar-card
        entity: sensor.ups_load
        name: "Load"
        animation:
          state: 'on'
          speed: 2
        positions:
          indicator: 'off'

  - type: entities
    entities:
      - type: custom:hui-element
        card_type: entities
        entities:
          - type: custom:hui-element
            card_type: picture
            image: 'https://pi-hole.net/wp-content/uploads/2018/12/pihole-text-logo-white.png'
            tap_action:
              action: url
              url_path: 'http://10.0.0.6/admin/index.php'
          - sensor.pihole_status
          - entity: sensor.pi_hole_ads_percentage_blocked_today
            name: "Blocked Today"
          - entity: sensor.pi_hole_domains_blocked
            name: "Domains on Blocklist"
          - type: custom:hui-element
            card_type: custom:mini-graph-card
            entities:
              - entity: sensor.pi_hole_ads_blocked_today
                name: "Queries blocked today"
                unit: 'Blocked'
                color: '#FF0F00'
              - entity: sensor.pi_hole_dns_queries_today
              - entity: sensor.pi_hole_dns_queries_forwarded
                color: '#4DFF00'
            show:
              points: false
              legend: false
            line_width: 2
            hours_to_show: 72
          - entity: sensor.pi_hole_dns_queries_cached
            name: "Cached"
          - entity: sensor.pi_hole_dns_unique_domains
            name: "Unique Domains"
