---

- alias: "Count Home Assistant log entries"
  id: e4653437-0a17-41d2-b14d-eaa1399cf890
  trigger:
    - trigger: event
      event_type: system_log_event
      event_data:
        level: ERROR
      id: 'error'
    - trigger: event
      event_type: system_log_event
      event_data:
        level: WARNING
      id: 'warning'
  action:
    - choose:
      - conditions:
          condition: trigger
          id: 'warning'
        sequence:
          action: counter.increment
          entity_id: counter.home_assistant_warning
      - conditions:
          condition: trigger
          id: 'error'
        sequence:
          action: counter.increment
          entity_id: counter.home_assistant_errors
  mode: queued
  max: 20
  max_exceeded: silent

- alias: "Reset Home Assistant log entries"
  id: e5cb265d-697d-4a35-8415-5f6aa1253558
  trigger:
    trigger: homeassistant
    event: start
  action:
    action: counter.reset
    entity_id:
      - counter.home_assistant_errors
      - counter.home_assistant_warning
