---

- alias: "Guest - Disable guest mode"
  id: 9e82409c-df7b-43fd-ad61-aa993570d5c8
  trigger:
    platform: zone
    entity_id:
      - person.yuval
      - person.tohar
    zone: zone.home
    event: enter
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.guest_mode
    - service: script.speech_engine
      data:
        message: >
          {{
            [
              "Guest Mode has been disabled and normal automations will continue.",
              "I have disabled guest mode and have resumed normal operations! ",
              "Disabling guest mode! "
            ] | random
          }}
