---

- alias: "Cover - Close when leaving"
  id: 2fe7cf5a-c7a3-4cfb-b1cb-ec9f2728b498
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  condition:
    - "{{ not is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    service: cover.close_cover
    data:
      entity_id: cover.living_room_shutter
