---

- alias: "Cover - Morning Cover"
  id: 3e52818c-536a-4e9e-b92f-088e60a03070
  description: Open shutter in the morning
  trigger:
  - platform: time
    at: 06:10:00
  condition:
  - condition: device
    device_id: 4d583bc6566c64342a0ac46e031fbe37
    entity_id: device_tracker.yuval
    type: is_home
  action:
  - device_id: 182e26f6c4cae7c966762eeb23f0754a
    entity_id: cover.shellyswitch25_c45bbe76536e
    type: open
