---

- alias: "Cover - Open on arrival"
  id: c5c5bc9b-4297-4ddd-b789-fb2211d11fab
  trigger:
    - platform: zone
      entity_id:
        - person.yuval
        - person.tohar
      zone: zone.home
      event: enter
  condition:
    condition: numeric_state
    entity_id: sensor.living_room_shutter_position
    below: 50
  action:
    service: cover.open_cover
    data:
      entity_id: cover.living_room_shutter
