---

- alias: "Cover: Living Room Shutter Schedule"
  id: 3e52818c-536a-4e9e-b92f-088e60a03070
  mode: restart
  trigger:
    - { id: 'weekday_open', trigger: time, at: '06:15:00' }
    - { id: 'weekday_close', trigger: time, at: '23:00:00' }
    - { id: 'shabbat_open', trigger: time, at: '08:00:00' }
    - { id: 'shabbat_close', trigger: time, at: input_datetime.shabbat_lights_off_time }
  condition:
    - condition: state
      entity_id: group.person
      state: 'home'
    - condition: template
      value_template: >
        {% set shabbat = is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') %}
        {% set tid = trigger.id if trigger is defined else 'manual' %}
        {{ (tid in ['weekday_open', 'weekday_close'] and not shabbat) or
           (tid in ['shabbat_open', 'shabbat_close'] and shabbat) }}
  action:
    - choose:
        - conditions: "{{ trigger.id in ['weekday_open', 'shabbat_open'] }}"
          sequence:
            - action: cover.open_cover
              target:
                entity_id: cover.living_room_shutter
            - choose:
                - conditions: "{{ trigger.id == 'weekday_open' and state_attr('sun.sun', 'elevation') | float(10) < 5 }}"
                  sequence:
                    - action: light.turn_on
                      target:
                        entity_id: light.pergola_light
                    - delay: "00:20:00"
                    - action: light.turn_off
                      target:
                        entity_id: light.pergola_light
        - conditions: "{% set tid = trigger.id %}
            {% set not_sukkot = state_attr('sensor.jewish_calendar_holiday', 'id') not in ['sukkot', 'hol_hamoed_sukkot'] %}
            {% set guest_ok = is_state('input_boolean.guest_mode', 'off') %}
            {{ (tid == 'weekday_close' and guest_ok and not_sukkot) or (tid == 'shabbat_close' and not_sukkot) }}"
          sequence:
            - action: cover.close_cover
              target:
                entity_id: cover.living_room_shutter
