---

- alias: "Cover - Close living room shutter on Shabbat night"
  id: 67d159ff-76fd-4ea6-9134-8e2237032966
  trigger:
    platform: time
    at: input_datetime.shabbat_lights_off_time
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
    - "{{ not is_state_attr('sensor.jewish_calendar_holiday', 'id', 'sukkot') }}"
  action:
    service: cover.close_cover
    data:
      entity_id: cover.living_room_shutter

- alias: "Cover - Shabbat Morning Cover"
  id: 5959bb5b-c629-4371-8434-6679c295d52c
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - "{{ is_state('group.person', 'home') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    service: cover.open_cover
    data:
      entity_id: cover.living_room_shutter
