---

- alias: "Turn on Kids light"
  id: 3a9d0a6d-5e1a-4db8-b27f-39439539b18a
  trigger:
    trigger: time
    at: '19:00:00'
  condition:
    - "{{ is_state('group.person', 'home') }}"
  action:
    action: light.turn_on
    data:
      entity_id:
        - light.harel_bed_harel_bed_light
        - light.rotem_bed_rotem_bed_light
      color_temp_kelvin: 3600

- alias: "Turn off Harel light"
  id: 4d564ae1-c9c0-4892-88bc-d986d8bd9bf0
  trigger:
    trigger: time
    at: '20:30:00'
  action:
    action: light.turn_off
    data:
      entity_id:
        - light.harel_bed_harel_bed_light
        - light.rotem_bed_rotem_bed_light

- alias: "Kids light alarm mode"
  id: 773491ad-c84f-486a-a55d-dc167ab494ea
  trigger:
    - trigger: state
      entity_id: binary_sensor.oref_alert_preemptive_update
      to: 'on'
      id: 'pre'
    - trigger: state
      entity_id: binary_sensor.oref_alert
      to: 'on'
      id: 'on'
    - trigger: state
      entity_id: binary_sensor.oref_alert
      to: 'off'
      id: 'off'
  condition:
    - "{{ is_state('group.person', 'home') }}"
  action:
    choose:
      - conditions:
          condition: trigger
          id: 'pre'
        sequence:
          action: light.turn_on
          data:
            entity_id:
              - light.harel_bed_harel_bed_light
              - light.rotem_bed_rotem_bed_light
            brightness_pct: 100
            color_name: yellow
            transition: 0
      - conditions:
          condition: trigger
          id: 'on'
        sequence:
          action: light.turn_on
          data:
            entity_id:
              - light.harel_bed_harel_bed_light
              - light.rotem_bed_rotem_bed_light
            brightness_pct: 100
            color_name: red
            transition: 0
      - conditions:
          condition: trigger
          id: 'off'
        sequence:
          action: light.turn_off
          data:
            entity_id:
              - light.harel_bed_harel_bed_light
              - light.rotem_bed_rotem_bed_light
            transition: 10
