---

- alias: "Lights - Disable false use"
  id: c4d8a631-0c8f-46a3-8f38-5acde5a35cb3
  trigger:
    - platform: state
      entity_id: light.bathroom_light
      to: 'on'
      id: 'on'
    - platform: state
      entity_id: light.bathroom_light
      to: 'off'
      id: 'off'
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'on') }}"
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: 'on'
          sequence:
            - delay: 1
            - service: light.turn_off
              data:
                entity_id: light.bathroom_light
        - condition: trigger
          id: 'off'
          sequence:
            - delay: 1
            - service: light.turn_on
              data:
                entity_id: light.bathroom_light
