---

- alias: "Lights - Turn on Living-room lights in workday morning"
  id: ab50f735-f05f-454e-813c-0ed8cdd4a51e
  trigger:
    platform: time
    at: '06:10:00'
  condition:
    - "{{ is_state('binary_sensor.workday_sensor', 'on') }}"
    - "{{ is_state('group.person', 'home') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room_lights
      kelvin: 3800
      brightness_pct: 100
      transition: 600
