---

- alias: "Lights - Turn on the Master-bedroom lights in a workday morning"
  id: cb2d8573-74f4-440c-9b2e-23057b5e492c
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - "{{ is_state('binary_sensor.workday_sensor', 'on') }}"
    - "{{ is_state('group.person', 'home') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.master_bedroom_light
