---

- alias: "Turn off outdoor lights when cover is closed"
  id: ce5e2bb0-ce4b-4e48-92fe-2dd05453047b
  trigger:
    platform: state
    entity_id: cover.living_room_shutter
    to: 'off'
    for:
      minutes: 5
  action:
    action: light.turn_off
    data:
      entity_id:
        - light.pergola_light
        - light.shed_light
