---

- alias: "Set Light scene"
  id: 8db9bb26-06a4-4315-a70b-72acfb0a5171
  trigger:
    platform: state
    entity_id: input_select.light_presets
  action:
    action: scene.turn_on
    data:
      entity_id: >-
        {% if trigger.to_state.state == 'Romance' %}
          scene.romance
        {% elif trigger.to_state.state == 'Morning' %}
          scene.morning
        {% elif trigger.to_state.state == 'Evening' %}
          scene.evening
        {% elif trigger.to_state.state == 'Shabbat eve' %}
          scene.shabbat_eve
        {% elif trigger.to_state.state == 'Shabbat day' %}
          scene.shabbat_day
        {% endif %}
