---

- alias: "Lights - Sukkah lights on"
  id: 72cdbac3-f4ad-477a-acdf-21dd3e57e7e3
  trigger:
    - id: 'sunset'
      platform: sun
      event: sunset
      offset: '-02:00:00'
    - id: 'off'
      platform: time
      at: input_datetime.shabbat_lights_off_time
  condition: "{{ is_state_attr('sensor.jewish_calendar_holiday', 'id', ['sukkot', 'hol_hamoed_sukkot', 'hoshana_raba']) }}"
  action:
    choose:
      - conditions:
        - condition: trigger
          id: 'sunset'
        sequence:
          service: light.turn_on
          data:
            entity_id: light.pergola_light
      - conditions:
        - condition: trigger
          id: 'off'
        sequence:
          service: light.turn_off
          data:
            entity_id: light.pergola_light
