---

- alias: "Notify for full batteries"
  id: 7cbcf6ee-ceb0-4190-b1aa-127ec17979df
  trigger:
    - platform: template
      id: 'yuval'
      value_template: "{{ is_state('sensor.yuval_battery_level', '100') }}"
    - platform: template
      id: 'tohar'
      value_template: "{{ is_state('sensor.tohar_battery_level', '100') }}"
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
    - condition: time
      after: '06:00:00'
      before: '22:00:00'
  action:
    - choose:
      - conditions:
        - condition: trigger
          id: 'yuval'
        - "{{ is_state('person.yuval', 'home') }}"
        sequence:
          service: notify.nest_mini
          data:
            message: "הסוללה של יובל טעונה במלואה"
      - conditions:
        - condition: trigger
          id: 'tohar'
        - "{{ is_state('person.tohar', 'home') }}"
        sequence:
          service: notify.nest_mini
          data:
            message: "הסוללה של טוהר טעונה במלואה"
