---

- alias: "Notify - Dishwasher complete"
  id: 261dd058-e6bf-47f9-ac37-320d132a5010
  trigger:
    platform: state
    entity_id: sensor.400090386855001425_bsh_common_status_operationstate
    to:
      - 'Finished'
      - 'BSH.Common.EnumType.OperationState.Finished'
  action:
    service: notify.family
    data:
      title: "Dishwasher Finished"
      data:
        message: "Dishwasher finished"
        image: '/local/assets/notification_images/dishwasher.jpg'
