---

- alias: "Notify for high AQI in the living room"
  id: 1a6cb8ea-3ac5-44fd-ab5a-cf73ef44d10c
  trigger:
    - platform: numeric_state
      entity_id: sensor.particulate_matter_10_0um_concentration_in_living_room
      above: 50
      for:
        minutes: 10
    - platform: numeric_state
      entity_id: sensor.particulate_matter_2_5um_concentration_in_living_room
      above: 50
      for:
        minutes: 10
  condition: "{{ is_state('binary_sensor.bathroom_door', 'off') }}"
  action:
    service: notify.mobile_app_yuval_phone
    data:
      title: "אויר לא נקי בסלון"
      message: "כדאי לאוורר את הבית"
