---

- alias: "Red Alert notification"
  id: dd1aa657-f774-4826-9afb-9eaec8c889e1
  trigger:
    platform: state
    entity_id: binary_sensor.oref_alert
    to: 'on'
  condition: "{{ is_state('group.person', 'home') }}"
  action:
    - action: light.turn_on
      entity_id: light.yeelight_ceilb_0x179e0932
    - action: light.turn_on
      data:
        entity_id:
          - light.yeelight_ceilb_0x179e0932_ambilight
          - light.wall_lights
        color: red
    - action: notify.family
      data:
        title: "צבע אדום"
        message: "טלמון"
        data:
          timeout: 300
          priority: high
    - wait_for_trigger:
        platform: state
        entity_id: binary_sensor.oref_alert
        to: 'off'
    - if:
        condition: time
        before: '07:00:00'
        after: '21:00:00'
      then:
        action: light.turn_off
        data:
          entity_id:
            - light.yeelight_ceilb_0x179e0932_ambilight
            - light.wall_lights
      else:
        action: scene.turn_on
        data:
          entity_id: scene.morning
          transition: 300
