---

- alias: "Red Alert"
  id: dd1aa657-f774-4826-9afb-9eaec8c889e1
  trigger:
    platform: state
    entity_id: binary_sensor.red_alert
    to: 'on'
  condition: "{{ is_state('group.person', 'home') }}"
  action:
    service: notify.family
    data:
      title: "צבע אדום"
      message: "טלמון"
      data:
        timeout: 120
        priority: high
