---

- alias: "Notify - Shabbat"
  id: c5553611-fb7b-42d7-80af-2608a31c2c25
  description: "Notify 30 minutes and 10 minutes before Shabbat"
  trigger:
    - platform: state
      entity_id: binary_sensor.shabbat_30_min_notification_trigger
      to: 'on'
    - platform: state
      entity_id: binary_sensor.shabbat_10_min_notification_trigger
      to: 'on'
  condition:
    - condition: time
      weekday:
        - fri
    - "{{ is_state('group.person', 'home') }}"
  action:
    - choose:
        - conditions:
            - "{{ is_state('binary_sensor.shabbat_30_hmin_notification_trigger', 'on') }}"
          sequence:
            - service: notify.mobile_app_yuval
              data:
                title: "שבת שלום!"
                message: "זכרת להכין מיחם ונרות?"
            - service: script.notify_for_shabbat
        - conditions:
            - "{{ is_state('binary_sensor.shabbat_10_min_notification_trigger', 'on') }}"
          sequence:
            - service: notify.family
              data:
                title: "שבת שלום!"
                message: "שבת נכנסת בעוד 10 דקות."
