---

- alias: "Notify - Shabbat"
  id: c5553611-fb7b-42d7-80af-2608a31c2c25
  description: "Notify 30 minutes and 10 minutes before Shabbat"
  trigger:
    - platform: state
      id: '30_min'
      entity_id: binary_sensor.shabbat_30_min_notification_trigger
      to: 'on'
    - platform: state
      id: '10_min'
      entity_id: binary_sensor.shabbat_10_min_notification_trigger
      to: 'on'
  condition:
    - condition: time
      weekday:
        - fri
    - "{{ is_state('group.person', 'home') }}"
  action:
    - choose:
        - conditions:
          - condition: trigger
            id: '30_min'
          sequence:
            - service: notify.mobile_app_yuval
              data:
                title: "שבת שלום!"
                message:  "מיחם, נרות ומקרר"
            - service: script.notify_for_shabbat
        - conditions:
          - condition: trigger
            id: '10_min'
          sequence:
            - service: notify.family
              data:
                title: "שבת שלום!"
                message: "שבת נכנסת בעוד 10 דקות."
                data:
                  image: '/local/assets/notification_images/Shalom_Aleichem.jpg'

- id: b603f3d9-5075-40b6-a2d2-9f5caf26a368
  alias: "Shabbat selection"
  description: ''
  use_blueprint:
    path: vorion/actionable-notifications-for-android.yaml
    input:
      second_action:
      - service: input_boolean.turn_off
        data: {}
        target:
          entity_id: input_boolean.at_home
      notify_device: a2af0c46177d1a180dc3590956202f0c
      trigger_entity: binary_sensor.shabbat_30_min_notification_trigger
      persistent_notification: true
      first_action:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id: input_boolean.at_home
      action_1_title: בבית
      action_2_title: לא בבית
      notification_title: שבת בבית?
