---

- alias: "Notify - Shabbat"
  id: c5553611-fb7b-42d7-80af-2608a31c2c25
  description: "Notify 30 minutes and 10 minutes before Shabbat"
  trigger:
    - platform: state
      id: '30_min'
      entity_id: binary_sensor.shabbat_30_min_notification_trigger
      to: 'on'
    - platform: state
      id: '10_min'
      entity_id: binary_sensor.shabbat_10_min_notification_trigger
      to: 'on'
  condition:
    - condition: time
      weekday:
        - fri
    - "{{ not is_state('zone.home', 0) }}"
  action:
    - choose:
        - conditions:
          - condition: trigger
            id: '30_min'
          sequence:
            - service: notify.mobile_app_yuval
              data:
                title: "שבת שלום!"
                message:  "מיחם, נרות ומקרר"
            - service: script.notify_for_shabbat
        - conditions:
          - condition: trigger
            id: '10_min'
          sequence:
            - service: notify.family
              data:
                title: "שבת שלום!"
                message: "שבת נכנסת בעוד 10 דקות."
                data:
                  image: '/local/assets/notification_images/Shalom_Aleichem.jpg'
