---

- alias: "Notify - Shabbat"
  id: c5553611-fb7b-42d7-80af-2608a31c2c25
  description: "Notify 30 minutes and 10 minutes before Shabbat"
  trigger:
    - platform: template
      id: '30_min'
      # value_template: >-
      #   {{ now() >= states('sensor.jewish_calendar_upcoming_candle_lighting') | as_datetime - timedelta(minutes = 30) }}
      value_template: >-
        {% set lighting = today_at((states('sensor.jewish_calendar_upcoming_candle_lighting') | as_datetime | as_local).time()) %}
        {{ now() - timedelta(minutes = 30) >= lighting }}
    - platform: template
      id: '10_min'
      value_template: >-
        {% set lighting = today_at((states('sensor.jewish_calendar_upcoming_candle_lighting') | as_datetime | as_local).time()) %}
        {{ now() - timedelta(minutes = 10) >= lighting }}
  condition:
    - or:
      - condition: time
        weekday:
          - fri
      - condition: template
        value_template: >-
          {{ is_state_attr('sensor.jewish_calendar_holiday', 'type_id', 2) }}
    - "{{ is_state('group.person', 'home') }}"
  action:
    choose:
      - conditions:
        - condition: trigger
          id: '30_min'
        sequence:
          - service: notify.mobile_app_yuval
            data:
              title: "שבת שלום!"
              message:  "מיחם, נרות ומקרר"
          - service: script.notify_for_shabbat
      - conditions:
        - condition: trigger
          id: '10_min'
        sequence:
          - service: notify.family
            data:
              title: "שבת שלום!"
              message: "שבת נכנסת בעוד 10 דקות."
              data:
                image: '/local/assets/notification_images/Shalom_Aleichem.jpg'
