---

- alias: "Shabbat notification"
  id: c5553611-fb7b-42d7-80af-2608a31c2c25
  description: "Notify 30 minutes and 10 minutes before Shabbat"
  trigger:
    - trigger: time
      id: '30_min'
      at:
        entity_id: sensor.jewish_calendar_upcoming_candle_lighting
        offset: "-00:30:00"
    - trigger: time
      id: '10_min'
      at:
        entity_id: sensor.jewish_calendar_upcoming_candle_lighting
        offset: "-00:10:00"
  condition:
    - or:
      - condition: time
        weekday:
          - fri
      - condition: template
        value_template: >-
          {{ is_state_attr('sensor.jewish_calendar_holiday', 'type_id', 2) }}
    - "{{ is_state('group.person', 'home') }}"
  action:
    choose:
      - conditions:
        - condition: trigger
          id: '30_min'
        sequence:
          - action: notify.mobile_app_yuval
            data:
              title: "שבת שלום!"
              message:  "מיחם, נרות ומקרר"
          - action: script.turn_on
            data:
              entity_id: script.notify_for_shabbat
      - conditions:
        - condition: trigger
          id: '10_min'
        sequence:
          - action: notify.family
            data:
              title: "שבת שלום!"
              message: "שבת נכנסת בעוד 10 דקות."
              data:
                image: '/local/assets/notification_images/Shalom_Aleichem.jpg'
