---

- alias: 'Notify - Unavailable lights'
  id: 26879041-377a-47bb-acdb-e684ba45c5e2
  mode: restart
  trigger:
    platform: state
    entity_id:
      - light.master_bedroom_light
      - light.kitchen_ceiling_light
      - light.yeelight_ceilb_0x179e0932
      - light.yeelight_color_0x12ab4331
      - light.yeelight_color_0x12bfc0a1
      - light.bathroom_light
      - light.corridor_light
      # - light.wled_harel_bed
      # - light.wled_rotem_bed
    to: 'unavailable'
    for: '00:05:00'
  action:
    service: persistent_notification.create
    data_template:
      title: "Light Offline"
      message: >-
        the {{ trigger.entity_id }} went offline at {{ now().strftime("%m/%d/%Y %H:%M:%S") }}

- alias: 'Notify - Unavailable devices'
  id: 58a57846-29da-4bb1-b40e-4926049b6f1c
  mode: restart
  trigger:
    platform: state
    entity_id:
      - switch.vent
      - switch.ensuite_heater
      - switch.boiler
    to: 'unavailable'
    for: '00:05:00'
  action:
    service: persistent_notification.create
    data_template:
      title: "Device Offline"
      message: >-
        the {{ trigger.entity_id }} went offline at {{ now().strftime("%m/%d/%Y %H:%M:%S") }}
