---

- alias: 'Unavailable devices notification'
  id: 58a57846-29da-4bb1-b40e-4926049b6f1c
  mode: restart
  trigger:
    - platform: state
      entity_id:
        - switch.vent
        - switch.ensuite_heater
        - switch.boiler
        - switch.shabbat_plate
        - switch.washing_machine
        - switch.spa_9cd951_switch
        - switch.laptop_9cd97f_switch
        - fan.kids_bedroom_fan
        - fan.master_bedroom_fan
        - media_player.tv
        - remote.tv
      to: 'unavailable'
      for: '00:05:00'
      id: 'devices'
    - platform: state
      entity_id:
        - light.master_bedroom_light
        - light.kids_bedroom_light
        - light.bathroom_light
        - light.kitchen_ceiling_light
        - light.yeelight_ceilb_0x179e0932
        - light.yeelight_color_0x12ab4331
        - light.yeelight_color_0x12bfc0a1
        - light.shed_light
        - light.pergola_light
      to: 'unavailable'
      for: '00:05:00'
      id: 'lights'
  action:
    choose:
      - conditions:
          condition: trigger
          id: 'devices'
        sequence:
          service: persistent_notification.create
          data_template:
            title: "Device Offline"
            message: >-
              the {{ trigger.entity_id }} went offline at {{ now().strftime("%m/%d/%Y %H:%M:%S") }}
      - conditions:
          condition: trigger
          id: 'devices'
        sequence:
          service: persistent_notification.create
          data_template:
            title: "Light Offline"
            message: >-
              the {{ trigger.entity_id }} went offline at {{ now().strftime("%m/%d/%Y %H:%M:%S") }}
