---

- alias: "Notify - Washing complete"
  id: 2e8e8a2d-5d76-41ab-808c-5bb7d0302c88
  trigger:
    entity_id: sensor.washing_maching_is_running
    platform: state
    to: 'off'
    for:
      minutes: 3
  action:
    service: notify.family
    data:
      message: "Washing machine finished"
      data:
        image: 'https://i.kym-cdn.com/photos/images/newsfeed/001/237/748/a8e.jpg'
