###
# Mold Indicator
###
- platform: mold_indicator
  name: 'Bathroom Mold Indicator'
  indoor_temp_sensor: sensor.bathroom_temperature
  indoor_humidity_sensor: sensor.bathroom_humidity
  outdoor_temp_sensor: sensor.outside_temps
  calibration_factor: 2.0
