---

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  ap:
    ssid: "${upper_devicename}_fallback_hotspot"
    password: !secret ap_passwd

captive_portal:
logger:
api:
ota:
  platform: esphome
