---

substitutions:
  devicename: bathroom-multisensor
  upper_devicename: "Bathroom"
  template_id: bathroom

<<: !include .base.yaml
<<: !include .multisensor_base.yaml

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2
