---

substitutions:
  devicename: ble_hub
  upper_devicename: "BLE Hub"
  template_id: ble_hub

esphome:
  name: ble-hub
  platform: ESP32
  board: esp32dev

logger:
api:
ota:

wifi:
  ssid: !secret ssid
  password: !secret wifi_passwd
  manual_ip:
    static_ip: !secret static_ble_hub
    gateway: !secret gateway
    subnet: 255.255.255.0
  ap:
    ssid: "${upper_devicename}_fallback_hotspot"
    password: !secret ap_passwd

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 20s

ble_client:
  - mac_address: FE:7A:A8:35:67:53
    id: mi_band_3
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from BLE device");
  - mac_address: F8:71:96:00:C9:D3
    id: amazefit_gts
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to BLE device");
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from BLE device");

binary_sensor:
  - platform: ble_presence
    mac_address: FE:7A:A8:35:67:53
    name: "Yuval Mi Band 3"
  - platform: ble_presence
    mac_address: F8:71:96:00:C9:D3
    name: "Tohar Amazefit gts"

sensor:
  - platform: ble_rssi
    mac_address: FE:7A:A8:35:67:53
    name: "Mi Band 3 RSSI"

  - platform: ble_rssi
    mac_address: F8:71:96:00:C9:D3
    name: "Amazefit gts RSSI"
