---

substitutions:
  devicename: eink
  upper_devicename: "EInk"
  template_id: eink

esphome:
  name: eink
  platform: ESP32
  board: esp32dev

logger:
api:
ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  manual_ip:
    static_ip: !secret static_eink
    gateway: !secret gateway
    subnet: 255.255.0.0
  ap:
    ssid: "${upper_devicename}_fallback_hotspot"
    password: !secret ap_passwd

captive_portal:

spi:
  clk_pin: 18
  mosi_pin: 23

font:
  - file: 'fonts/unispace_bd.ttf'
    id: unispace
    size: 20

binary_sensor:
  - platform: gpio
    name: "${devicename}_sw1"
    id: epaper_sw1
    pin:
      number: GPIO39
      inverted: True

display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo-dke
    update_interval: 1m
    full_update_every: 280
    rotation: 270
    lambda: |-
      it.print(0, 0, id(unispace), "Hello World!");
