---

substitutions:
  devicename: ensuite_multisensor
  upper_devicename: "Ensuite"
  template_id: ensuite

esphome:
  name: $devicename
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret ssid
  password: !secret wifi_passwd
  manual_ip:
    static_ip: !secret static_ensuite
    gateway: !secret gateway
    subnet: 255.255.255.0
  ap:
    ssid: "${upper_devicename}_fallback_hotspot"
    password: !secret ap_passwd

captive_portal:
logger:
  level: VERBOSE
api:
ota:

i2c:
  sda: D2
  scl: D1
  scan: True
  frequency: 400kHz

mcp23017:
  - id: mcp23017_hub

binary_sensor:
  - platform: gpio
    pin:
      number: D6
    name: "${upper_devicename} Motion"
    device_class: motion
    filters:
      - delayed_on: 500ms
      - delayed_off: 30s
  # - platform: gpio
  #   name: "${upper_devicename} Door"
  #   device_class: door
  #   pin:
  #     mcp23xxx: mcp23017_hub
  #     number: 8
  #     mode: INPUT_PULLUP
  #     inverted: false
  - platform: status
    name: "${upper_devicename}"

sensor:
  - platform: bme280
    temperature:
      name: "${upper_devicename} Temperature"
      id: ${template_id}_temperature
      oversampling: 16x
    pressure:
      name: "${upper_devicename} Pressure"
    humidity:
      name: "${upper_devicename} Humidity"
      id: ${template_id}_humidity
    address: 0x76
    update_interval: 60s

  - platform: bh1750
    name: "${upper_devicename} Illuminance"
    id: ${template_id}_illuminance
    address: 0x23
    measurement_duration: 69
    update_interval: 60s
  - platform: template
    name: "${upper_devicename} Percieved Brightness"
    id: ${template_id}_percieved_brightness
    unit_of_measurement: "%"
    lambda: |-
      return ((log10(id(${template_id}_illuminance).state) / 5) * 100);

switch:
  - platform: restart
    name: "Restart ${upper_devicename}"
  - platform: gpio
    name: "${upper_devicename} Shabbat Select"
    pin:
      number: D5
      inverted: yes
