---

substitutions:
  devicename: ensuite-multisensor
  upper_devicename: "Ensuite"
  template_id: ensuite

<<: !include .base.yaml
<<: !include .multisensor_base.yaml

esphome:
  name: $devicename

esp8266:
  board: nodemcuv2
