---

substitutions:
  devicename: harel_bed
  upper_devicename: "Harel Bed"
  template_id: arel_bed

esphome:
  name: $devicename

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  manual_ip:
    static_ip: 10.0.0.71
    gateway: 10.0.0.1
    subnet: 255.255.0.0
  ap:
    ssid: "${upper_devicename}_fallback_hotspot"
    password: !secret ap_passwd

captive_portal:
logger:
api:
ota:
  platform: esphome

# i2c:
#   sda: D2
#   scl: D1
#   scan: True
#   frequency: 400kHz

# uart:
#   rx_pin: D7
#   tx_pin: D8
#   baud_rate: 9600

# mcp23017:
#   - id: mcp23017_hub

binary_sensor:
  # - platform: gpio
  #   pin:
  #     number: D6
  #   name: "${upper_devicename} Motion"
  #   device_class: motion
  #   filters:
  #     - delayed_on: 1500ms
  #     - delayed_off: 30s
  # - platform: gpio
  #   name: "${upper_devicename} Window"
  #   device_class: window
  #   pin:
  #     mcp23xxx: mcp23017_hub
  #     number: 8
  #     mode: INPUT
  #     inverted: false
  - platform: status
    name: "${upper_devicename}"

sensor:
  # - platform: bme280
  #   temperature:
  #     name: "${upper_devicename} Temperature"
  #     id: ${template_id}_temperature
  #     oversampling: 16x
  #   pressure:
  #     name: "${upper_devicename} Pressure"
  #   humidity:
  #     name: "${upper_devicename} Humidity"
  #     id: ${template_id}_humidity
  #   address: 0x76
  #   update_interval: 60s

  # - platform: bh1750
  #   name: "${upper_devicename} Illuminance"
  #   id: ${template_id}_illuminance
  #   address: 0x23
  #   update_interval: 60s
  # - platform: template
  #   name: "${upper_devicename} Percieved Brightness"
  #   id: ${template_id}_percieved_brightness
  #   unit_of_measurement: "%"
  #   lambda: |-
  #     return ((log10(id(${template_id}_illuminance).state) / 5) * 100) ;

  # - platform: sds011
  #   pm_2_5:
  #     name: "2.5µm Particles in the ${upper_devicename}"
  #   pm_10_0:
  #     name: "10µm Particles in the ${upper_devicename}"

# switch:
#   - platform: gpio
#     name: "${upper_devicename} Shabbat Select"
#     pin:
#       number: D4
#       inverted: yes
  
button:
  - platform: restart
    name: "Restart ${upper_devicename}"

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812x
    pin: D5
    num_leds: 59
    name: "Harel Light"
    effects:
      - pulse:
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
      - addressable_scan:
      - addressable_scan:
          name: Scan Effect With Custom Values
          move_interval: 100ms
          scan_width: 6
      - addressable_twinkle:
      - addressable_twinkle:
          name: Twinkle Effect With Custom Values
          twinkle_probability: 5%
          progress_interval: 4ms
      - addressable_random_twinkle:
      - addressable_random_twinkle:
          name: Random Twinkle Effect With Custom Values
          twinkle_probability: 20%
          progress_interval: 32ms
      - addressable_fireworks:
      - addressable_fireworks:
          name: Fireworks Effect With Custom Values
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: false
          fade_out_rate: 120
      - addressable_flicker:
      - addressable_flicker:
          name: Flicker Effect With Custom Values
          update_interval: 16ms
          intensity: 5%
