---

- alias: "Vent - bind to light-on"
  id: 954e3adf-5ebf-49c3-b112-1adab2df757e
  trigger:
    platform: state
    entity_id: light.bathroom_light
    to: 'on'
  condition: "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    service: switch.turn_on
    data:
      entity_id: switch.vent

- alias: "Vent - bind to light-off"
  id: f36fc2be-3f7c-4d70-8391-edfda7504a18
  trigger:
    platform: state
    entity_id: light.bathroom_light
    to: 'off'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.vent
