---

- alias: "Vent - bind to light"
  id: 9b100fdf-a569-4c1c-bb3c-a5c5270e2a5c
  trigger:
    platform: state
    entity_id: light.bathroom_light
    to: 'on'
  action:
    service: switch.turn_on
    data:
      entity_id: switch.vent
