---

- alias: "Vent - bathroom humidity is ok"
  id: 7d57c758-0175-46ff-a266-a8dd5670f71e
  trigger:
    platform: time_pattern
    minutes: 5
  condition:
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
    - "{{ is_state('binary_sensor.bathroom_light_is_on', 'off') }}"
    - condition: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 70
  action:
    service: switch.turn_off
    data:
      entity_id: switch.vent

- alias: "Vent - Turn off after time has passed"
  id: ac975e09-9643-495c-8ab0-3364d8e67ab8
  trigger:
    platform: state
    entity_id: light.bathroom_light
    to: 'on'
    for: '00:30:00'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.vent
