---

- alias: "Vent - Bathroom humidity is OK"
  id: 7d57c758-0175-46ff-a266-a8dd5670f71e
  trigger:
    platform: time_pattern
    minutes: 5
  condition:
    - "{{ is_state('light.bathroom_light', 'off') }}"
    - condition: numeric_state
      entity_id: sensor.bathroom_humidity
      below: 70
  action:
    service: switch.turn_off
    data:
      entity_id: switch.vent

- alias: "Vent - Turn-off after time has passed"
  id: ac975e09-9643-495c-8ab0-3364d8e67ab8
  trigger:
    platform: state
    entity_id: switch.vent
    to: 'on'
    for: '00:30:00'
  action:
    service: switch.turn_off
    data:
      entity_id: switch.vent

- alias: "Vent - Turn-off on arrival"
  id: 5b178ad8-c0b0-41d8-9934-0576f3429dcd
  trigger:
    - platform: zone
      entity_id:
        - person.yuval
        - person.tohar
      zone: zone.home
      event: enter
  action:
    service: switch.turn_off
    data:
      entity_id: switch.vent
