---

vacuum_reset_sensor:
  alias: "Reset cliff sensors"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.mi_vacuum
      params: sensor_dirty_time

vacuum_reset_filter:
  alias: "Reset Filter"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.mi_vacuum
      params: filter_work_time

vacuum_reset_side_brush:
  alias: "Reset side brush"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.mi_vacuum
      params: side_brush_work_time

vacuum_reset_main_brush:
  alias: "Reset main brush"
  icon: mdi:restart
  sequence:
    service: vacuum.send_command
    data:
      command: reset_consumable
      entity_id: vacuum.mi_vacuum
      params: main_brush_work_time
