---

vacuum_set_silent:
  alias: "Set Silent"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.mi_vacuum
      fan_speed: Silent

vacuum_set_standard:
  alias: "Set Standard"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.mi_vacuum
      fan_speed: Standard

vacuum_set_medium:
  alias: "Set Turbo"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.mi_vacuum
      fan_speed: Medium

vacuum_set_turbo:
  alias: "Set Max"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.mi_vacuum
      fan_speed: Turbo
