---

vacuum_set_silent:
  alias: "Set Quiet"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.roborock_s7
      fan_speed: Quiet

vacuum_set_standard:
  alias: "Set Balanced"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.roborock_s7
      fan_speed: Balanced

vacuum_set_medium:
  alias: "Set Turbo"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.roborock_s7
      fan_speed: Turbo

vacuum_set_turbo:
  alias: "Set Max"
  icon: mdi:fan
  sequence:
    service: vacuum.set_fan_speed
    data:
      entity_id: vacuum.roborock_s7
      fan_speed: Max
