---

title: "Bathroom"
icon: mdi:shower
cards:
  - type: custom:decluttering-card
    template: multisensor
    variables:
      - room: bathroom

  - type: entities
    entities:
      - sensor.bathroom_mold_indicator
