---

id: homelab
title: "Homelab"
icon: mdi:server
cards:
  - type: entities
    entities:
      - entity: sensor.myip
        name: "DNS IP"

  - type: entities
    title: "NanoPi NEO 3"
    entities:
      - type: custom:hui-element
        card_type: picture
        image: 'https://leeselectronic.com/c/3280-category_default/nano-pi.jpg'
      - type: custom:decluttering-card
        template: system_monitor
        variables:
          - cpu_usage: processor_use_percent
          - cpu_temps: processor_temperature
          - ram_usage: memory_use_percent
      - type: custom:bar-card
        entities:
          - entity: sensor.disk_use_percent
            name: "Storage"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100
  - type: entities
    title: "NanoPi NEO 2"
    entities:
      - type: custom:hui-element
        card_type: picture
        image: 'https://leeselectronic.com/c/3280-category_default/nano-pi.jpg'
      - entity: sensor.npn2_containers_active
        name: "Active Containers"
      - type: custom:decluttering-card
        template: system_monitor
        variables:
          - cpu_usage: npn2_cpu_used
          - cpu_temps: npn2_cpu_thermal_1_temperature
          - ram_usage: npn2_ram_used_percent

  - type: entities
    title: "RaspberryPi 2"
    entities:
      - type: custom:hui-element
        card_type: picture
        image: 'http://magazine.odroid.com/wp-content/uploads/fig-02-omv.png'
      - type: custom:decluttering-card
        template: system_monitor
        variables:
          - cpu_usage: rpi2_cpu_used
          - cpu_temps: rpi2_cpu_thermal_1_temperature
          - ram_usage: rpi2_ram_used_percent
      - type: custom:bar-card
        entities:
          - entity: sensor.rpi2_used_percent
            name: "Storage"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100
          - entity: sensor.omv_media
            name: "Media drive"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100
          - entity: sensor.omv_m_bm_m_om_bm_m_om_wm_pm_wm_m_wm_m_wm
            name: "1TB drive"
            severity:
              - color: '#FF0F00'
                from: 91
                to: 100
