---

ac_cool:
  alias: "Cool"
  icon: mdi:snowflake
  sequence:
    - service: climate.turn_on
      data:
        entity_id: climate.living_room
    - delay: 2
    - service: climate.set_hvac_mode
      data:
        hvac_mode: cool
      target:
        entity_id: climate.living_room
    - delay: 2
    - service: climate.set_temperature
      data:
        temperature: 21
      target:
        entity_id: climate.living_room

ac_heat:
  alias: "Heat"
  icon: mdi:fire
  sequence:
    - service: climate.turn_on
      data:
        entity_id: climate.living_room
    - delay: 2
    - service: climate.set_hvac_mode
      data:
        hvac_mode: heat
      target:
        entity_id: climate.living_room
    - delay: 2
    - service: climate.set_temperature
      data:
        temperature: 25
      target:
        entity_id: climate.living_room
