---

light_set_warm:
  alias: "Set Warm"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.wall_lights
        effect: 'Stop'
    - service: light.turn_on
      data:
        entity_id:
          - light.yeelight_ceilb_0x179e0932
          - light.kitchen_ceiling_light
          - light.wall_lights
        brightness_pct: 100
        kelvin: 3800

light_set_daylight:
  alias: "Set Daylight"
  sequence:
    - service: light.turn_on
      data:
        entity_id: light.wall_lights
        effect: 'Stop'
    - service: light.turn_on
      data:
        entity_id:
          - light.yeelight_ceilb_0x179e0932
          - light.kitchen_ceiling_light
          - light.wall_lights
        brightness_pct: 100
        kelvin: 6500

light_set_date_night:
  alias: "Set Date Night"
  sequence:
    - service: light.turn_on
      data:
        entity_id:
          - light.yeelight_ceilb_0x179e0932
          - light.kitchen_ceiling_light
        brightness_pct: 20
        kelvin: 3600
    - service: light.turn_on
      data:
        entity_id: light.wall_lights
        effect: 'Romance'

light_set_morning:
  alias: "Set Morning"
  sequence:
    service: light.turn_on
    data:
      entity_id: light.wall_lights
      brightness_pct: 100
      kelvin: 3700
      transition: 300
