---

notify_for_shabbat:
  alias: "Notify for Shabbat"
  description: "Give a Shabbat brief on a media device using tts"
  sequence:
    - service: media_player.volume_set
      entity_id: media_player.living_room
      data:
        volume_level: 0.9
    - delay: 3
    - service: notify.nest_mini
      data:
        message: >-
          "השבת פרשת {{ states('sensor.jewish_calendar_parshat_hashavua') }},
          כניסת שבת בשעה {{ as_timestamp(states('sensor.jewish_calendar_upcoming_shabbat_candle_lighting')) | timestamp_custom('%I:%M') }},
          צאת השבת בשעה {{ as_timestamp(states('sensor.jewish_calendar_upcoming_havdalah')) | timestamp_custom('%I:%M') }}."
    - service: media_player.volume_set
      entity_id: media_player.living_room
      data:
        volume_level: 0.5
